guardrail-dev/guardrail

build.sbt
modules/codegen/src/main/scala/com/twilio/swagger/codegen/ClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/Common.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/core/StructuredLogger.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/generators/Http4sGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/generators/ScalaParameter.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/package.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/AliasProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/ArrayProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/ClientGeneratorTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/EnumProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/ModelProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/ProtocolSupportTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/protocol/terms/ServerTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/terms/CoreTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/terms/FrameworkTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/terms/ScalaTerms.scala
modules/codegen/src/main/scala/com/twilio/swagger/codegen/terms/SwaggerTerms.scala
src/test/scala/generators/Http4s/Client/Basic.scala
src/test/scala/generators/Http4s/Client/DefaultParameters.scala
src/test/scala/package.scala

Because of the update to cats 1.1.0, all of the dependencies needed to
be updated, too. There were also breaking api changes to both cats,
http4s, and fs2:
cats:
1. Inject -> InjectK
1. Coproduct -> EitherK
1. EitherT.left now infers from F[A]
1. No more need for sequenceU*, traverseU* due to Unapply updates
fs2:
1. fs2.Strategy -> ExecutionContext
1. fs2.Task -> cats.effect.IO
http4s:
1. Most types now take a `F[_] : Effect`
1. Request -> Request[F[_]]
1. Entity*coder[A] -> Entity*coder[F[_], A]
1. jsonEncoderOf[A] -> jsonEncoderOf[F[_], A]
I tested code generation with petstore.yaml and the resulting project
succeeded.

Update cats to 1.1.0 (and dependencies)

---

build.sbt
modules/codegen/src/main/scala/com/twilio/swagger/codegen/SwaggerUtil.scala
src/test/scala/generators/AkkaHttp/PropertyExtractors.scala

While parsing swagger with additionalProperties, not all definitions are
resolved in swagger-parser < 1.0.34.
(https://github.com/swagger-api/swagger-parser/pull/602)
This brings us to the most recent version of swagger-parser on the 1.x
line.
Fixes: #40

Update swagger-parser to fix definition parse bug

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
src/test/scala/core/Types.scala

- Wrapping java API accesses with `Option` even though `UntypedProperty` should catch these cases
- Removing orphaned `toCamelCase` methods
- Adding `toString` to `ScalaParameter` for ease of use

NPE and cleanup

---

.gitignore
build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/sample/src/main/resources/petstore.json
modules/sample/src/main/scala/support/PositiveLong.scala
modules/sample/src/test/scala/core/RoundTrip.scala
src/test/scala/tests/generators/akkaHttp/AkkaHttpServerTest.scala
src/test/scala/tests/generators/akkaHttp/StaticParametersTest.scala
src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala

Resolves: #70 #71 #72
Explicitly calling out how JSON parsing fallback is handled for fields:
Submitting via:
curl ... -F foo=bar
is treated the same way as:
curl ... -F 'foo="bar"'
This is somewhat undesirable, but avoids us accidentally including
unescaped doublequotes into string values. This sets a general precident
of:
curl ... -F 'foo=\"bar\"'
being the blessed way to ensure JSON tokens are not accidentally
processed when they were intended to be included in the value.

Custom multipart decoder

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala

This compiles, but I'm pretty unfamiliar with how Guardrail works, so I'm not sure if there are any other changes I need to make along with it. Just submitting this so we can iterate.

Added implicit show for Java URL type

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala
modules/codegen/src/main/scala/com/twilio/guardrail/WriteTree.scala

This provides non-`println` versions of `unsafeReadSwagger` and `unsafeWriteTree` for use in build tools
Primary motivator is to make the sbt plugin fail if it can't read specification files

Error reporting and logging

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/extract/VendorExtension.scala
modules/codegen/src/test/scala/core/issues/Issue105.scala

Making x-scala-type work for non-string types

---

modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/AkkaHttpServerTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/StaticParametersTest.scala

I've been getting increasingly frustrated with my play project continually recompiling my guardrail routes and finally dug in to find out what was happening. In short, there are a couple of places in the route generation pipeline for akka http server that use groupBy and never sort the results, producing non-determinstic ordering in the Routes.scala files, causing the Scala compiler to have to compile and slow everything down.
I've hacked in sorting on the places I've found, and it resolves my issue. The failing tests are due to hardcoded output in a different order. I'm not sure how you're getting ahold of the generated .scala files to put in the tests so I thought I'd throw this up for comment.
Fixes https://github.com/twilio/sbt-guardrail/issues/8

Sort routes to ensure deterministic output

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue127.scala
modules/sample/src/main/resources/issues/issue127.yaml

scala.meta seems to not automatically lift `q"(..${List(q"foo")})"` into `q"Tuple1(foo)"`. This makes sense, though ends up requiring special casing. This PR implements the special casing required.

Resolving bug where formData with only parameter would cause runtime failures

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4s.scala
modules/codegen/src/main/scala/com/twilio/guardrail/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/CoreTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/CoreTerms.scala
modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala

Breaking out `ScalaLanguage` from the last little bits of `CoreTerm`/`CodegenApplication`
This pushes language evaluation to the very edge of the world for the CLI interpreter by prepending the language desired for processing all arguments to the first CLI argument (ie: `cli.sh scala --client ...`)

Coreterm LanguageAbstraction

---

.gitignore
build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
modules/codegen/src/test/scala/core/issues/Issue43.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/CustomHeaderTest.scala
modules/sample/src/main/resources/issues/issue148.yaml
modules/sample/src/test/scala/core/issues/Issue148.scala

- Added error messages to polymorphic discriminators (previous error: `scala.MatchError: foo (of class java.lang.String)`)
- Exposed underlying circe decoding errors
- Removed incorrect usage of `NoContentException`
Initial work towards #148, actually exposing validation errors in clients and servers. Customization will be more tricky, still need to think about how that will work.

Exposing helpful error messages

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue127.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala
modules/sample/src/main/resources/issues/issue143.yaml
modules/sample/src/test/scala/core/issues/Issue143.scala

Resolves #143 
This moves the exception handler up before the route -- the exception handler was previously not used due to being in the wrong place.
Additionally, calling `dest.delete()` _immediately_ upon any exception, to avoid the condition where an exception happens inside `UnmarshalToFile`, preventing the file handle from being added to the `AtomicReference[List[File]]`s to clean up.

Making akka-http FormData return 413 instead of 500, delete failed files

---

COMPATIBILITY.md
docs/book.md

Related to #161 
I've created [a new repo](https://github.com/blast-hardcheese/guardrail-version-isolation) to permit easily trying out different combinations of library versions and guardrail versions. With that, I was able to better narrow down versions that are generally compatible.

Restructuring compatibility matrix

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue122.scala
modules/codegen/src/test/scala/core/issues/Issue165.scala
modules/codegen/src/test/scala/tests/generators/http4s/Http4sServerTest.scala

Fix double trailing slash for http4s server generator.
The issue:
When we have empty path for method like in swagger file below:
```yaml
swagger: 2.0
info:
description: Some description
schemes:
- http
paths:
/:
post:
x-scala-package: somePackage
operationId: someOperationId
consumes:
- application/json
produces:
- application/json
responses:
200:
```
generated server consumes only requests for this path with double slash like so:
http://localhost//

fix double trailing slash for http4s server

---

modules/codegen/src/main/scala/com/twilio/guardrail/CodegenTarget.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/test/scala/core/issues/Issue166.scala

https://github.com/twilio/guardrail/issues/166
This adds the ability to generate _just_ models from swagger docs. This is my first PR here, so please let me know how this looks!
I know https://github.com/twilio/sbt-guardrail is what i've used in the past to build these, will I need to submit a PR to that project so 
```
guardrailTasks in Compile := List(
Models(file("petstore.yaml"))
)
```
We can handle something like ^^

Adding the ability to generate just models with kind of Models

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/sample/src/main/resources/issues/issue164.yaml

Fixes #164
Allow clients to use LocalDate parameters
With the implict LocalDate provided the generated client test passes

Fixes #164  Implict LocalDate for clients

---

.gitignore
.scalafmt.conf
.travis.yml
CONTRIBUTING.md
build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
project/plugins.sbt

- Disabling `scalafmtOnCompile`
- Requiring scalafmt for CI
- Ensuring all source files are tracked (related: https://github.com/scalameta/sbt-scalafmt/issues/11, https://github.com/scalameta/sbt-scalafmt/issues/12)
- Switching from `"com.lucidchart" % "sbt-scalafmt"` to `"com.geirsson" % "sbt-scalafmt"` to get `scalafmtCheck`

Adjusting scalafmt to be less obnoxious during development

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala

The http4s generator uses the 'ci' method when getting headers in a case-insensitive way. The import to pull in this from an implicit conversion is missing. This PR adds the

Add import needed for "ci" method in http4s generator (Issue #180)

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala

The code generated for AkkaHttp is not compiling for Scala 2.11 The error is like following:
```
target/scala-2.11/src_managed/main/com/codacy/worker/api/specification/AkkaHttpImplicits.scala:92:46: missing parameter type for expanded function ((x$8) => {
[error]   <synthetic> <artifact> val x$9 = acc(value);
[error]   x$8.$colon$colon(x$9)
[error] })
[error]       accumulator.updateAndGet(acc(value) :: _)
[error]                                              ^
[error] one error found
```
Here you have the trivial fix.

Fix compilation of AkkaHttpImplicits for Scala 2.11

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/DropwizardRoundTripTest.scala
modules/sample-dropwizard/src/test/scala/helpers/MockHelpers.scala

This is _mostly_ user-invisible.  The base response class now holds the entity body (if any), and is parameterized on the entity body's type.  Now the resource class method doesn't need to do `instanceof` checks for each response type to attempt to extract entity bodies and can instead just pull out an `Optional<T>` from the abstract base class.
Depends on https://github.com/twilio/guardrail/pull/199

Make DW server response classes simpler for the resources to use

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala

Turns out you're not supposed to use `@HttpMethod` on resource methods directly, but instead create your own annotations that are themselves annotated with `@HttpMethod`.

Generate @TRACE and @PATCH annotations for Dropwizard

---

.gitignore
build.sbt

This avoids a weird situation where a source root is a subdirectory of another source root, and makes it so the sample code generation gets cleaned up with `sbt clean`.  The gitignore rules become simpler, and IDEs don't get confused about where the generated code lives.

Move generated samples under target/ and refactor build.sbt a bit

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala

* Use [google-java-format](https://github.com/google/google-java-format) to format the generated Java code.  I don't love everything about Google's code style guidelines, but this output is _way_ better than javaparser's not-so-pretty printer.
* Sort class body declarations in a sane way so things look nice.

Java code formatting

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/DropwizardRoundTripTest.scala

* Allow `WriteClient` to return a `List[WriteTree]` (previously just a single `WriteTree`).
* Emit client response definitions into their own files.
* Sort class members of the client and response definition classes.

Java AHC cleanups

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Error.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/CoreTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/CoreTerms.scala
modules/sample/src/main/resources/petstore.json

- Combine `Target` and `CoreTarget`, at least in structure initially
- Unify the three different kinds of log handling
- Consolidate common build idioms from different build tooling into a set of reusable functions
- Using `NonEmptyList` to represent argument lists for different languages

Unify build tool codepaths

---

modules/codegen/src/main/scala/com/twilio/guardrail/ClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/client/ClientTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/client/ClientTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala

It's used a bunch of places in the core and in generators and is by no means http4s-specific.

Move Response/Responses out of Http4sHelper and into common code

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala

- The previous attempt of `extra` was unsuccessful. Instead, now consumers with custom frameworks can:
```scala
val scalaInterpreter = FooCoreTermInterp[ScalaLanguage](
"internal-framework", chainFrameworkMappings({
case "internal-framework" => InternalFrameworkGenerator
}, CLI.scalaInterpreter.frameworkMapping), {
_.parse[Importer].toEither.bimap(err => UnparseableArgument("import", err.toString), importer => Import(List(importer)))
}
)
```
It's not perfect, but it reduces duplication and prevents forgetting to include new frameworks in internal forks

Restructuring CLI one more time to re-enable overriding CoreInterp

---

modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala
modules/sample-dropwizard/src/test/java/core/Dropwizard/DropwizardResourceTest.java
modules/sample-dropwizard/src/test/scala/core/Dropwizard/DropwizardRoundTripTest.scala

Moves DW response definitions back into the handler interface, as inner classes.

DW responses back in handler

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/sample/src/main/resources/issues/issue215.yaml

We can use x-scala-type: SomeType in both parameters and definitions. We can also use x-scala-type: some.qualified.Type in definitions -- but not in parameters. Using that in parameters crashes guardrail.
This change relaxes the match that was crashing.

don't constrain x-scala-type in params to Type.Name.  fixes #214

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientHelpers.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/codegen/src/main/scala/com/twilio/guardrail/languages/JavaLanguage.scala

Nothing major here, just fixing some type parameter constraints and moving some code around so it's more accessible to extensions.

Java misc fixes

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala

Not needed yet here, but needed for downstream implementations that include tracing.

AsyncHttpClient: pass clientName to CallBuilder if tracing enabled

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue165.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala

Both http4s generated server and client require implicit instance of `Effect[F]`. This seems as way too powerful constraint that limits certain use cases. One example would be `type F[T] = ReaderT[IO, Context, T]`. It does not have instance of `Effect`. If we were to change the requirement from `Effect` to `Async`, it would remove this limitation.

Use cats effect Async instead of Effect

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/DropwizardRoundTripTest.scala

Arguably the old way made the generated code a little nicer to read, but the aesthetics for the user were ugly with the type param, and especially the wildcard type param in the handler signatures.
This effectively reverts acd9f592478867c8ac54337c8deaa06d9ce55dfa

Go back to non-parameterized resource classes for DW servers

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala

Same as https://github.com/twilio/guardrail/pull/212 but for the http4s client.

http4s client: prefix identity with Predef

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue126.scala
modules/codegen/src/test/scala/core/issues/Issue127.scala
modules/codegen/src/test/scala/tests/core/PathParserSpec.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/AkkaHttpServerTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/CustomHeaderTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/StaticParametersTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue148.scala
modules/sample/src/main/resources/issues/issue45.yaml
support/write-pathological.sh

Resolves #45 
Finally got around to it, @manuelbernhardt!
Important notes
===
This changes the parse order of akka-http directives. Previously, we attempted to parse the entity before parsing the headers. Now, we parse everything we get in the base HTTP message before starting to parse the entity. This permits route failover before parsing the entity.
~The only caveat is that this does not support more than 22 parameters in a single group (path, query string, headers, form fields). This may need to change, but the MVP here is to just split the individual groups; in the future, we'll need to divide the individual matchers into 22 parameter groups, but this should at least give a little bit of breathing room.~ Now it does!
Turns out http4s also had a 22-parameter limit for the union between …

Adding support for too many arguments

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/sample/src/main/resources/issues/issue249.yaml
notes/0.47.1.md

Resolves: #249 
- Resolves syntactic ambiguity for akka-http parameter matching
- Additionally, for optional `type: array` parameters, adds a `filter(_.nonEmpty)`, removing the possibility of `Some(Nil)`
- Also fixing optional list parameter matching compiler error in http4s that was exposed when adding the tests for akka-http.

Disambiguate akka-http when optional parameter lists are specified

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/codegen/src/test/scala/com/twilio/guardrail/generators/syntax/JavaSyntaxTest.scala
modules/sample/src/main/resources/issues/issue264.yaml

Addresses https://github.com/twilio/guardrail/issues/264
This also cleans up some deficiencies with our case converters, namely not handling spaces as separators in the original identifier, and not handling numbers as the initial character in a grouping when converting to pascal case.

Fix enum naming

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala

If a property name is a reserved word, it'll get escaped with an underscore appended.  But when we capitalize that word and prepend "with", it's no longer reserved and doesn't need the ugly trailing underscore anymore.

Unescape property names when building with*() methods for POJOs

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala

* Use unboxed types in parameters and fields where possible
* Fix setting extended/implemented types (before it was setting all as `extends`, rather than putting the interfaces on `implements`, which would generate invalid code).
* Redesign how polymorphism works (see commit comments for details).

Miscellaneous Jackson fixes

---

MIGRATING.md
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/package.scala
modules/codegen/src/test/scala/tests/core/CaseConvertersTest.scala
modules/sample-http4s/src/test/scala/generators/Http4s/RoundTrip/Http4sFormDataTest.scala

Completely new approach; see comments in the code for a description.
Addresses https://github.com/twilio/guardrail/issues/153 finally.

Rewrite case converters and add tests

---

docs/book.md

Parameter descriptions provide good insight on specificities of what values are expected for each parameter. The field is optional and is described as such

Add missing description field to operation params

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/sample-dropwizard/src/test/java/core/Dropwizard/DropwizardMultiPartTest.java
modules/sample-dropwizard/src/test/java/core/Dropwizard/DropwizardResourceTest.java
modules/sample-dropwizard/src/test/scala/core/Dropwizard/DropwizardRoundTripTest.scala

This is to prevent us from generating uncompileable multiple-inheritance hierarchies.  It works like this:
1. If there's more than one parent class that has a discriminator, we throw an error.
2. If there's a single parent that has a discriminator, we extend from that parent class.  If there are other parents, we flatten them so the generated class has the properties of all those other parents.
3. If there's just a single parent, we extend from that parent class.
4. Otherwise there's no composition or polymorphism going on, so we just emit a class that extends from nothing.
Unfortunately this necessitated removing the static `builder()` method from the POJO class, because you can't have a static method in a subclass with the same arg list that has a different return type.  (Which is an …

Flatten Jackson inheritance hierarchies where needed

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue260.scala

Fix for issue: https://github.com/twilio/guardrail/issues/260
Using date as path param type in multiple paths will no longer generate multiple LocalDateVar objects.
This might also apply to other 'non native' path param types.

Fixed issue 260

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/Issue263.scala
modules/sample/src/main/resources/additional-properties.yaml

Also parse both in a safer way that makes it more clear where errors lie.

Fix copypasta in JacksonGenerator causing maps to be lists

---

build.sbt

Adding the Eclipse JDT formatter for Java code broke assembly because of a bunch of duplicate files in the Eclipse JARs that need merge strategies.

Fix sbt assembly command

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/AsyncHttpClientContentHeaderTest.scala
modules/sample-dropwizard/src/test/scala/helpers/WireMockSupport.scala
modules/sample/src/main/resources/contentType-textPlain.yaml

Take two of https://github.com/twilio/guardrail/pull/278
Adds text/plain and application/octet-stream support for AHC request and response bodies.
Also improves error reporting from the Java code formatter rather than just dumping a stack trace to console.

Better content type support for AsyncHttpClient

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala

So this is embarrassing.  Not sure how the original PR tests passed, since they're failing now...

Use the actual operation body types in getBestConsumes()

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala

The default exception/error message thrown is next to useless, so use the two-arg variant that takes a description that tells the caller what is missing.
Also adds a `java.util.Optional` import to JacksonGenerator so we don't have to keep using the unsightly fully-qualified name.

Add a description to requireNonNull() calls

---

modules/sample-dropwizard/src/test/scala/core/Dropwizard/AsyncHttpClientContentHeaderTest.scala
modules/sample/src/main/resources/contentType-textPlain.yaml

The akka-http server generator doesn't properly support text/plain response bodies yet, so avoid conflicting with other tests in the DW test.

Add an extra operation to the text/plain test

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolElems.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/PolyProtocolTerm.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonPolyMappingTest.scala
modules/sample/src/main/resources/polymorphism-mapped.yaml

Addresses https://github.com/twilio/guardrail/issues/193 (for both Circe and Jackson).
I had to make a little compromise rather than doing a major refactor: I implemented a mini-protocol-elem-resolver (_very_ mini tho) for the discriminator mapping values.  As you probably remember, protocol elements are generated like so:
1. Separate schemas into regular and poly.
2. Render all polymorphic ADTs.
3. Render all regular protocol objects.
4. Resolve all polymorphic ADTs.
5. Resolve all regular protocol objects.
The problem is that there's a semi-circular dependency.  During step 1, the hierarchies for poly ADTs are built.  However, that requires that steps 4 and 5 already be done, because discriminator mapping values can reference other (polymorphic or not) schemas.  And the rendering steps …

Implement support for OpenAPI v3 schema discriminator mapping

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/sample-akkaHttp/src/test/scala/generators/AkkaHttp/Client/contentType/AkkaHttpTextPlainTest.scala
modules/sample-http4s/src/test/scala/generators/Http4s/Client/contentType/Http4sTextPlainTest.scala

Not sure why PR validation didn't catch this.  (And I bet this showed up as a warning, but I missed it :( ).

Fix discriminator filter in circe protocol trait generation

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/extract/Extractable.scala
modules/codegen/src/main/scala/com/twilio/guardrail/extract/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/sample-akkaHttp/src/test/scala/generators/Circe/CirceRedactionTest.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonRedactionTest.scala
modules/sample/src/main/resources/redaction.yaml

Redacts fields in circe- and jackson-generated objects' `toString` methods.

Add basic redaction via new vendor extension 'x-data-redaction'

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala

We give an `Option[SecurityRequirements]` to terms that might need to do stuff with security.  The `SecurityRequirements` case class contains a list of requirements.  If that list is empty, there's no point in having ` SecurityRequirements` instance at all, so we guarantee that there will be at least one item in the list, and also guarantee that the item in the list is a non-empty map, since it's pointless for it to be empty.

Use NonEmptyList/NonEmptyMap for SecurityRequirements

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala
modules/codegen/src/test/scala/tests/core/RequestBodiesTest.scala

The `resolve` option to the parser (which we use) appears to auto-resolve references to parameters, headers, and responses (at least), but for some reason doesn't do the same for requestBodies.

Add OpenApi v3 components/requestBodies ref support

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/sample/src/main/resources/additional-properties.yaml

Fixes properties that are a reference to a map type, or properties that are maps with the value as a reference to another map type.
Previously the type name would just be inlined, but that would fail to compile since it would reference a type that wasn't emitted at all.
Also fixes a weird reference in JacksonGenerator to a java type called `Array` that doesn't exist; assuming that was copypasta from the circe generator.

additionalProperties $ref fixes

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue325.scala
modules/sample/src/main/resources/issues/issue325.yaml
modules/sample/src/main/resources/petstore.json

Resolves #324 
When multiple content types are specified in `consumes`, deduplicate the parameters and mark ones that don't explicitly occur across all media types as not required.

Deduplicate identical parameters across different contentTypes

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala

Since required properties are passed to the builder constructor, there's usually no need to be able to call `withSomeProperty(...)` to later set the value (again).  However, since I added the "copy" constructor for the builder, this would mean that you wouldn't be able to use that constructor and then modify the value of a required property, which greatly reduces its usefulness.  So, we remove that restriction and add a few more checks to ensure that the object remains consistent.

Allow overriding required POJO properties with builder methods

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Scala.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/test/scala/core/issues/Issue127.scala
modules/codegen/src/test/scala/core/issues/Issue260.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue325.scala
modules/sample/src/main/resources/issues/issue325.yaml

Resolves #312 
- Switches to `Unmarshaller`s for `formData` consumption to support both `application/x-www-form-urlencoded` _and_ `multipart/form-data`, depending on what's in `consumes`
- Relies heavily on parameter deduplication (#325)
- If any `consumes` are `application/x-www-form-urlencoded`, all `file` parameters are forced to be optional.

Akka form data consumption

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Scala.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/codegen/src/test/scala/com/twilio/guardrail/generators/ScalaParameterTestAdapter.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/AkkaHttpServerTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/CustomHeaderTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue148.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue184.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue325.scala
modules/sample-dropwizard/src/test/scala/helpers/MockHelpers.scala
modules/sample/src/main/resources/issues/issue184.yaml

#184 unmarshaller shuffle

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala

There is no need to import `org.http4s.client.blaze._` as it is client backend implementation specific namespace. I believe that generated code should be client backend agnostic.

Do not import blaze client for http4s

---

modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala

There is a support to generate only models already, it's just not exposed over CLI. This PR fixes it.
We use swagger not only for HTTP API definition, but also for definition of events schema. So it makes no sense for us to generate any kind of client/server code.
- [x ] I acknowledge that all my contributions will be made under the project's license.

Allow models to be generated from CLI

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue127.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/AkkaHttpServerTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/CustomHeaderTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala

Trying to fix codegen in #210 
When generating the akka code it does not compile. After removing it and compiling just the akka part it compiles in my tests. But seems like the tests in this repo fail. Any ideas?

fix: Remove extra apply in generated multiple query parameters

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/package.scala
modules/codegen/src/test/scala/core/issues/Issue166.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala

When generating only model classes, current behavior is to generate also a file with implicits for given framework. This effectively means that generated code has a build dependency on http4s/akka-http/... even though it's not needed.
This PR changes that such that no file with framework specific implicits is generated when generating model classes only.

Do not generate framework implicits when generating model only

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala

Add @Inject to Resource constructor making it available for
Dependency Injection frameworks.
Signed-off-by: Charlie Helin <chelin@twilio.com>

Adding support for DI (JSR-330)

---

build.sbt

Bumping bm4 to resolve unnecessary `[wartremover:NonUnitStatements] Statements must return Unit`s

Bumping better-monadic-for

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue105.scala
modules/codegen/src/test/scala/core/issues/Issue145.scala
modules/codegen/src/test/scala/core/issues/Issue222.scala
modules/codegen/src/test/scala/core/issues/Issue43.scala
modules/codegen/src/test/scala/swagger/protocols/BigObjectSpec.scala
modules/codegen/src/test/scala/tests/core/BacktickTest.scala
modules/codegen/src/test/scala/tests/core/DereferencingAliasesSpec.scala
modules/codegen/src/test/scala/tests/core/ScalaTypesTest.scala
modules/codegen/src/test/scala/tests/core/TypesTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/DefinitionSpec.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/PropertyExtractors.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/client/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/client/ParamConflictsTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/sample/src/main/resources/issues/issue351.yaml

Resolves #351 
Adding support for recursive object definitions

Issue 351 fix

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala

This PR largely applies to akka-http, though the intent is as more functionality gets fleshed out, more of the requirements will move to core and trickle out into the rest of the frameworks/languages.
- Starting with changing `consumes` to `NonEmptyList` (flipped for the akka-http client generator)
- Two new exceptions in cases where we don't have either `Free` or `Target` (these will continue to flag as warnings as time goes on, and will be resolved as we go back to reduce the number of warnings in the build, moving towards `-Wall`)
- Removing some NPEs in the 2to3 shim (we were doing stuff like `Option(getSchema.getType)`)
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the …

Safety and exhaustivity refactors

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue357.scala
modules/sample/src/main/resources/issues/issue357.yaml

Depends on #358 
Resolves #357 
#292 didn't fully resolve the problem, as query string parameters still used the old-style fallback parser.
I've added a test for it now, as well as deleting the dangerous unmarshaller entirely.

Unmarshaller shuffle redux

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonPolyMappingTest.scala
modules/sample/src/main/resources/polymorphism-mapped.yaml

For Jackson, we assume that polymorphic POJO discriminators are of type string, which is of course a bit limiting.  Ideally they can be any type, including enums.
Unfortunately, it's not possible for us to support any arbitrary type with how we handle discriminators right now, but we can at least explicitly support all primitive types, as well as enums.
Stuff I'm not happy about:
1. To figure out which type to use, we "reverse engineer" the parsed type that the core gives us.
2. If the type the core gives us isn't a recognized primitive type, or one of the types explicitly listed as being not supported, we just assume it's an enum type, which of course it may not be.  This will result in generated code that won't compile.  It would be better to present an error at generation time, but on …

Support arbitrary primitive types and enums as discriminators

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/codegen/src/test/scala/tests/core/TypesTest.scala

This PR bring support for generation of definition classes for objects that are inlined (they are defined with some other object definition). Current behavior is not to generate any definition class and just just `io.circe.Json` (scala). This PR significantly improves current situation.
Generated definitions for those classes are placed into a companion object. Name of a class is derived from a property for which the class was derived for. Please see a test if this is not clear.
A similar approach can be used for enums that are not defined on their own. Currently we use `String`. I plan to implement this as well, but in a separate PR to keep this one small.
> All third-party contributors acknowledge that any contributions they provide will be made under the same …

Generate definition classes for inlined objects

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/sample/src/main/resources/issues/issue364.yaml
project/src/main/scala/ExampleCase.scala

The goal is for generated Java definitions to have the correct package
defined in case the `dtoPackage` flag is provided.
This PR aims to address Issue #364 

Use correct package for Java definitions

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/test/scala/tests/core/TypesTest.scala
modules/sample/src/main/resources/additional-properties.yaml

The core doesn't really know how to emit objects like that (so it doesn't, and we end up with a compile error when building the generated classes).  At any rate, if there's a bare `object` type without any
properties, our assumption is that the user is expected to populate it with whatever data is applicable: arbitrary key/value pairs, primitive types, whatever; so in this case we should just use `objectType()` (`io.cire.Json` or Jackson `JsonNode`).
Issue introduced in https://github.com/twilio/guardrail/pull/356 -- unfortunately at the time we didn't have a specific test for this, so no surprise we didn't catch it.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source …

Don't generate an inline object for objects with no properties

---

modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala

I think sbt handles this reasonably (by hashing file contents), but it appears that maven pays more attention to file modification times.  It slows down things enough already that guardrail runs each time a build is run, but having to recompile files that haven't changed just adds insult to injury.
1. Running guardrail for the first time should have roughly the same performance (an extra `stat()` per file, which will fail since the file doesn't exist).
2. Running guardrail when files need to be updated will be either roughly the same or a bit slower, depending: a) if the file sizes are different, it's just a `stat()` plus integer comparison extra, so roughly the same; b) if the file sizes are the same, it has to read the existing file off disk and compare, so things will be a bit slower. …

Avoid rewriting files with identical contents

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue165.scala
modules/codegen/src/test/scala/core/issues/Issue225.scala
modules/sample/src/main/resources/issues/issue179.yaml

This PR fixes #179 
In summary, we don't use Http4sDsl for response construction, but we build `Response` manually instead. 

Fixes #179

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Header.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala
modules/sample/src/main/resources/response-headers.yaml

Issue #53 for http4s server/client, endpoints/akka clients

Issue #53 for http4s server/client, endpoints/akka clients

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerms.scala
modules/codegen/src/test/scala/core/issues/Issue255.scala
modules/codegen/src/test/scala/swagger/VendorExtensionTest.scala
modules/codegen/src/test/scala/tests/core/DereferencingAliasesSpec.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala
modules/sample/src/main/resources/alias.yaml
modules/sample/src/main/resources/binary.yaml
modules/sample/src/main/resources/issues/issue148.yaml
modules/sample/src/main/resources/petstore.json
modules/sample/src/main/resources/polymorphism-mapped.yaml
modules/sample/src/main/resources/polymorphism.yaml
modules/sample/src/main/resources/raw-response.yaml
project/src/main/scala/ExampleCase.scala

This PR solves #329 for http4s and somehow also improves situation mentioned in #255. 
To sum up all the changes done:
- We now use `fs2.Stream[F, Byte]` as a default binary data representation instead of `java.io.File`
- this somehow unifies binary data handling as some parts of generated code were already using `fs2.Stream[F, Byte]`  while some were using `java.io.File`.
- It means that response definition classes must be generic with `F[_]`. This generic parameter is added only when needed.
- When generating a client, we need to return `Resource[F, Something[F]]` instead of just `F[Something[F]]`. Again, `Resource` is only used when we determine it's really needed.
- Users can still provide custom type via `x-scala-type`, such as `Array[Byte]` or `fs2.Chunk[Byte]`. In those cases, we …

issue-329: binary support for http4s

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue405.scala
modules/sample/src/main/resources/issues/issue405.yaml

This fixes https://github.com/twilio/guardrail/issues/405 by removing the `contentRequiredUnmarshaller` from the generated form param parsing code. This prevented clients from sending empty string values to String form params which was a regression from earlier versions of guardrail. 
The `contentRequiredUnmarshaller` is not required because for other types, the type specific parser should fail on an empty string input, however for String this should be allowed.

Issue 405 Fix regression in empty string Form param handling in AkkaHttpServer 

---

COMPATIBILITY.md
build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Context.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Error.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaModule.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Module.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaModule.scala
modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue121.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue148.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue184.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue325.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue357.scala
project/plugins.sbt

Fixes #361 
I've removed the imports and added some documentation. There could be more places where documentation needs to be updated.

Remove generated io.circe.java8 imports and add documentation

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/sample/src/main/resources/polymorphism-nested.yaml

This fixes an issue that resulted into a code that was not possible to compile.
Essentially a wrong name of companion object was used when nested enum/case class was referenced.

Fixed handling of nested structures/enums when polymorphism is used

---

.github/workflows/ci.yml
.travis.yml
build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/codegen/src/test/scala/core/issues/Issue429.scala
modules/codegen/src/test/scala/tests/core/FullyQualifiedNames.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue121.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue184.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue325.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue357.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue405.scala
modules/sample-http4s/src/test/scala/core/issues/Issue121.scala

Resolves #443 
So, master started failing to compile after merging #434 due to some Scala-specific changes being applied directly in the "core" interpreter. This wasn't caught earlier because the Java tests haven't been run during the PR validation process.

Fix build and tests

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sHelper.scala

Starting the version 0.21 http4s requires to explicitly provide a transformation functor from G to F in EntityResponseGenerator. The following chores allow compiling generated code using both 0.20 and 0.21 http4s version. 
- [ √] I acknowledge that all my contributions will be made under the project's license.

Add support for http4s 0.21.x

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/extract/Extractable.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala

Some small changes to reduce the number of warnings during any given build
- Replacing `println` with `Target.raiseError`
- Using `@SuppressWarnings` for unavoidable stuff
- Using fluent API for javaparser instead of leaking non-unit statements
- Sinking non-unit statements to `_` in for comprehensions

Cleaning up warnings

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala

Removes unnecessary `any2stringadd`

Remove redaction any2stringadd warning

---

modules/codegen/src/main/scala/cats/free/Hacks.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/StructuredLogger.scala
modules/codegen/src/test/scala/core/GuardrailFreeHacksSuite.scala
modules/codegen/src/test/scala/core/StructuredLoggerSuite.scala

In an attempt to make it easier to debug either while developing or when running guardrail, this PR abuses the deferred nature of `Free` to dynamically inject logs every time there's a `FlatMapped(Suspend(term), f)`, which is the construct that maps to calling out to a member of a Free algebra.
Abusing package membership is necessary because there are no public functions on `Free` that expose the tree itself, only handling individual terms, like `mapK`.

Traversing Free structure to inject term logging

---

.travis.yml

Resolves #432
- According to [the docs](https://github.com/xerial/sbt-sonatype#commands), only `sonatypeBundleRelease` should be necessary.
- Also removing the JDK11 Matrix build, as it's very slow on Travis covered by Github Actions, and complicates the release process on every release (manual intervention is required to avoid conflicting releases)

Switching to sonatypeBundleRelease

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/Tracker.scala
modules/codegen/src/main/scala/com/twilio/guardrail/extract/Default.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala

Continuing to advance Tracker through the codebase, with a focus on removing warnings and pushing Tracker to where error logs are emitted so we can give contextual information.

Propagate tracker

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/package.scala
modules/codegen/src/test/scala/core/issues/Issue416.scala

Fixes issue #416 
Add a method to `com.twilio.guardrail.generators.syntax.RichString` to ensure a string is not capitalized, this is required as capitalised operationIds which are used in the creation of decoder names break the scalameta invariant check (I'm unsure of the actual root cause to this). Now, even when endpoints have capitalised operationIds and a body parameter then will now generate correctly.

Ensure Decoders for both Http4s and Akka are not capitalized when generating

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonBuilderParamTest.scala

Avoids runtime exceptions with the trade off that if you don't expect something you pass to be `null`, and it is, you might be confused.

Use Optional.ofNullable instead of .of where appropriate

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala

This restores the compatibility with Scala 2.11.
The root cause is:
https://github.com/circe/circe/issues/756

fix: Restore Scala 2.11 compatibility

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/Tracker.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/test/scala/core/issues/Issue370.scala
modules/codegen/src/test/scala/core/issues/Issue429.scala
modules/codegen/src/test/scala/core/issues/Issue43.scala
modules/codegen/src/test/scala/tests/core/BacktickTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/DefinitionSpec.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/EnumTest.scala

- Removing `hackyAdapt`
- Propagating `Tracker` more
- Switching from `map(_ => a)` to `Tracker.cloneHistory(...)` for visibility

Removing hackyadapt

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/sample-dropwizard/src/test/java/core/Dropwizard/DropwizardResourceTest.java

Previously they were just added to query/form/header params.

Add @NotNull annotation to DW body parameters

---

.github/workflows/ci.yml

Per discussion with GitHub engineers, '@v1' is preferred over '@v1.0.3'
The tag '@v1' is updated whenever GitHub makes a new release

use '@v1' for GitHub Actions

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/codegen/src/test/scala/com/twilio/guardrail/generators/syntax/JavaSyntaxTest.scala

Instead of overloading the user with mountains of stack traces, just print what the problem is

Trying a little harder to pull out a useful error message from ParseProblemException

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SerializationHelpers.scala
modules/sample-dropwizard/src/test/java/core/Dropwizard/DropwizardJsr310Test.java
modules/sample/src/main/resources/date-time.yaml

We can't use DW's built-in `AbstractParam` subclasses because they always return a JSON error response that can't be overridden in service code without a lot of pain.
This also allows us to avoid needing separate guardrail modules for DW7-9 and DW10+, as the JSR310 `AbstractParam` subclasses are in separate artifacts and have different package names for the two version ranges.
Addresses https://github.com/twilio/guardrail/issues/239

Replace JSR310 injection providers with DW AbstractParam

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Target.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaModule.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaModule.scala
modules/codegen/src/main/scala/com/twilio/guardrail/package.scala
modules/codegen/src/test/scala/core/GuardrailFreeHacksSuite.scala
modules/codegen/src/test/scala/core/StructuredLoggerSuite.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala

- Temporarily disables StructuredLogger
- Replaces `EitherT` in `Target` with a bespoke implementation

codegen performance improvements

---

.travis.yml

This shouldn't impact anything, but running `makeMicrosite` before `publishMicrosite` may be a workaround for https://github.com/47deg/sbt-microsites/issues/406

Going to try makeMicrosite before publishing

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/Tracker.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala

For failed type lookups, include the history of the object in the error message

Including Tracker history in FallbackPropertyTypeHandler

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala

- use exit status 0 to indicate success
- use exit status 1 to indicate failure

cli: set exit status

---

COMPATIBILITY.md
build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala
modules/codegen/src/test/scala/tests/core/FullyQualifiedNames.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala

Upgrade http4s and dependencies:
http4s 0.21.0
cats 2.1.0
cats-effect 2.1.1
circe 0.13
* scalac had troubles finding the correct lub in the generated code for the http4s client. Solved with explicit type annotations. I don't know why this suddenly became an issue. Also, quasiquotes is not my strong suite, so please review and suggest edits.
* The changes in `CirceVersion` is just cargo culting, not sure if it's necessary

Upgrade http4s, cats, cats-effect and circe

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
modules/sample/src/main/resources/conflicting-names.yaml

This PR fixes a use case (http4s server) where parameter name was also scala keyword. This currently generates pattern matching code with backticks. Unfortunately, backticks are used for referencing existing variable inside pattern matching. So they can't be used for variables such as `type`. This PR aims for at least partial fix. Generator now tries to detect it and "fix" it by prefix parameter name with underscore. Not perfect, nor terrible. 

Better parameter names handling in http4s server

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala

Include the parameter name in the  error messages

improve parameter error messages

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/codegen/src/test/scala/tests/core/TypesTest.scala
modules/sample-http4s/src/test/scala/core/issues/Issue542.scala
modules/sample/src/main/resources/base64.yaml

Handle byte string format according to specification

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientHelpers.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardHelpers.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/codegen/src/main/scala/com/twilio/guardrail/languages/JavaLanguage.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Content.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/AsyncHttpClientUtilsTest.java
modules/sample/src/main/resources/binary.yaml
modules/sample/src/main/resources/random-content-types.yaml

From the most important commit message:
This adds generic `TextContent` and `BinaryContent` classes that represent
arbitrary content-types outside of our main directly-supported types
(like application/json, text/plain, etc.).  The goal here is to
transparently support arbitrary text and binary types.
For example, imagine an API that handles document storage.  The API
would likely make use of JSON for handling metadata about documents, but
there could be endpoints that return the documents themselves.  It would
be nice if we could support, say, application/pdf documents without
having to special case every possible document type.
The classification of text vs. binary when it comes to the application/
registry is a bit fuzzy, since there's no encoding information attached
to the …

MIME type overhaul

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/CoreTarget.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Target.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaModule.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaModule.scala
modules/codegen/src/main/scala/com/twilio/guardrail/package.scala

Describing CoreTarget as a sealed abstract class, in preparation for adding StructuredLogger back

Remove EitherT from CoreTarget

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala

Jersey will look for a magic `fromString(String)` method in order to parse a string into an enum.  Renamed `parse()` to `fromString()` and added a `@Deprecated` compat version of `parse()`.

Fix Java enum usage as Jersey @*Param

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/CoreTarget.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Target.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/StructuredLogger.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaModule.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala

After flattening Target and CoreTarget into sealed abstract classes, it seems as though StructuredLogger can be reintroduced without significant performance penalties.
After ten iterations of running `sbt resetSample runScalaExample` in a bash `for` loop:
| master | this branch |
| ------ | ----------- |
| 0m55.430s | 0m50.572s |
| 0m56.836s | 0m53.420s |
| 1m0.381s  | 0m54.534s |
| 1m2.485s  | 0m56.867s |
| 1m2.684s  | 0m57.790s |
| 1m3.166s  | 0m59.800s |
| 1m3.836s  | 1m0.645s  |
| 1m5.988s  | 1m1.785s  |
| 1m6.346s  | 1m2.181s  |
| 1m8.693s  | 1m2.570s  |

Re-enable logger

---

build.sbt
modules/sample-dropwizard/src/test/java/core/Dropwizard/CharacterEncodingTest.java
modules/sample/src/main/resources/char-encoding/char-encoding-request-stream.yaml
modules/sample/src/main/resources/char-encoding/char-encoding-response-stream.yaml

I'm not sure how useful this is in general, but someone was running into character encoding issues, and I figured it was a good idea to eliminate guardrail as the cause.
Now, this doesn't _completely_ exonerate guardrail, since I had to just use `text/plain` for the body types for the test where I actually examine the bytes sent to/from the server.  Jackson (and circe) will do its own charset handling, as will the clients and servers when they marshal/unmarshal things like form params.  Unfortunately, I can't really hook into any of that at a useful level, so this is the best I can do.  I *do* verify that the strings round-trip ok for JSON & form-data, but that doesn't test that the bytes on the wire are correct.
> All third-party contributors acknowledge that …

Add DW test to verify character encoding of strings

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerms.scala

Threads through the info necessary to fix https://github.com/twilio/guardrail/issues/315 (though it does not actually attempt to fix it yet; current behavior is maintained).
Verified with a temp git repo in each of the `sample-*` dirs that generated output remains unchanged with these commits.
Note that the name of this branch lies, as I dropped the `always-camelsnake` bit after submitting.

Thread through required/nullable state

---

modules/codegen/src/main/scala/com/twilio/guardrail/ClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolElems.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
modules/codegen/src/main/scala/com/twilio/guardrail/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/client/ClientTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ArrayProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/EnumProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/PolyProtocolTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ProtocolSupportTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/CoreTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/framework/FrameworkTerms.scala
modules/codegen/src/test/scala/core/issues/Issue166.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala
modules/microsite/src/main/scala/DocsHelpers.scala

Using scalafix to rewrite all other interfaces not covered by #591 into Tagless Final-style. This does not actually alter the interpreters themselves, that will come in (a) subsequent PR(s).

Tagless final pt2

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Endpoints.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Framework.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4s.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/Dropwizard.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvc.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/client/ClientTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ArrayProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/EnumProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/PolyProtocolTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ProtocolSupportTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/CoreTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/framework/FrameworkTerms.scala

- Bubbling `FunctionK` up into each interface, to reduce churn in the future
- Adding `copy(...)` methods to TF interpreters
- Keeping TF -> Free transitional adapters for the next release

Tagless final pt3

---

support/write-release-template.sh

These changes were necessary to respond to https://github.com/twilio/guardrail/pull/542#issuecomment-613455200 while the major shifts to guardrail core are going on.
0.57.1 will be released shortly after, with only performance enhancements and some library upgrades.

Add support for releasing old versions to write-release-template.sh

---

modules/codegen/src/main/scala/com/twilio/guardrail/WriteTree.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
modules/codegen/src/test/scala/com/twilio/guardrail/core/WriteTreeSuite.scala

After doing some performance analysis, it seems as though a nontrivial amount of time is spent churning in scalameta's syntax renderer.
As a stopgap, we can thread the rendering function at the very least. There may be more gains possible by contributing back to scalameta (with the hope of having configurable syntax backends that don't flatten `for` comprehensions onto a single line!)

Rendering syntax for generated files inside Future

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/Target.scala
modules/codegen/src/test/scala/core/StructuredLoggerSuite.scala

So, attempting to run guardrail against the 5mb spec linked in https://github.com/twilio/sbt-guardrail/issues/56 OOM'd guardrail.
For now, trying to split the difference between logging functionality and performance by only enabling the logger if the user has explicitly chosen a log level on the CLI.
This'll require support in build tools if they want logging to be enabled, which will need to get removed once the logging infrastructure has moved to something a little more efficient, like slf4j.

Conditionally enable logger

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/shims/package.scala
modules/codegen/src/test/scala/tests/generators/dropwizard/server/DropwizardContentTypesTest.scala

If an error response has a body type, even if the success response does not, we should still generate a Produces annotation for the method.

 Fix missing Produces annotation when no 2xx response with body

---

modules/codegen/src/main/scala/com/twilio/guardrail/core/Tracker.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala
modules/codegen/src/test/scala/tests/generators/dropwizard/server/DropwizardContentTypesTest.scala

Resolves #619
- Making `flatDownField` more general, chaining Option to any `Applicative` + `MonoidK` combo for null safety while interoperating well with other container types
- Adding `unapply` for Tracker
- Providing a better error messages for validation errors with produces/consumes in the akka-http generator

Propagating tracker (#619)

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/LanguageTerms.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonNestedTest.scala

Java doesn't need it, as all declarations should end up as static members of their outer class.

Make WrapToObject optional

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/sample/src/main/resources/issues/issue622.yaml

Resolves #622 
Verified in the console:
```
scala> implicitly[AddArg[Option[Vector[Long]]]]
res0: issues.issue622.Implicits.AddArg[Option[Vector[Long]]] = issues.issue622.Implicits$AddArg$$anon$1@269e559f
scala> res0.addArg
def addArg(key: String,v: Option[Vector[Long]]): String
scala> res0.addArg("foo", Some(Vector(1, 2, 3, 4)))
res1: String = foo=1&foo=2&foo=3&foo=4
```

Adding List and Vector to form encoder lifters, AddArg

---

modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala

CLI warning does not match reality. This PR fixes that.

docs: fixed CLI warning

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/package.scala
modules/codegen/src/test/scala/tests/core/CaseConvertersTest.scala

Turns out the casing normalization code attempts to interpolate groups. `$1`/`$2`... etc turn out not to be escaped, causing unexpected oddities.
The generated names are stable, if not odd, so the underlying protocol is not impacted, but the generated interface is unpleasant.
This also addresses an edge case where `[A-Z][^A-Z]`, _intended_ to catch `ABCFoo`, turning it into `abcFoo`, ends up with `ABCFOO$` into `AbcfoO$`, which makes sense, but is odd.

Quoting issue

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue370.scala
modules/codegen/src/test/scala/core/issues/Issue43.scala
modules/codegen/src/test/scala/tests/core/BacktickTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/DefinitionSpec.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/EnumTest.scala

As recommended by https://nrinaudo.github.io/scala-best-practices/adts/product_with_serializable.html

Make circe enums extend Product & Serializable

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue126.scala
modules/codegen/src/test/scala/core/issues/Issue127.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/AkkaHttpServerTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/CustomHeaderTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/StaticParametersTest.scala
modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala

This addresses #643 I believe.

Path matcher before method matcher in Akka HTTP routes.

---

modules/microsite/docs/index.md
modules/microsite/docs/java/dropwizard/index.md
modules/microsite/docs/java/index.md
modules/microsite/docs/java/spring-mvc/index.md
modules/microsite/docs/scala/http4s/index.md
modules/microsite/src/main/resources/microsite/data/menu.yml

Trying to correct some of the documentation oddities, as well as suggest some direction for undocumented frameworks

Adding more useful documentation stubs

---

build.sbt

I read through scala-steward in order to figure out why library upgrades for sample subprojects weren't getting opened.
It turns out it's because the `stewardDependencies` task walks `libraryDependencies` for root and aggregated tasks.
Unfortunately, as `*Sample` projects are not designed to be aggregated (they don't pass `compile` unless we're running `testSuite`), it necessitated some hoop jumping.
A more long-term solution would be to modify scala-steward to be able to run the `stewardPlugin` against non-`root` projects, but as this is a fairly niche use case, I'm OK with this solution for now.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided …

Making scala-steward able to update deps for unlinked *Sample projects

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala

circe-generic has not been used for a long, long time

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala

When generating models only, the framework definitions of the server and client are not rendered.  However, the Shower class is still required for models, so move it into the framework support definitions list.

Move Shower class to framework def instead of server/client def

---

modules/codegen/src/main/scala/com/twilio/guardrail/extract/package.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/test/scala/core/issues/Issue314.scala
modules/microsite/docs/scala/akka-http/guardrail-extensions.md

Added a new flag `x-{jvm,scala,java}-class-prefix` to allow for an arbitrary class name in the generated code.

ISSUE-314: Allow custom class names for generated clients and server resources/handlers

---

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
modules/sample/src/main/resources/raw-response.yaml

Falling back to string type that we know works rather than the raw format type specified in the specification. This will ensure
that the unsupported format type will compile, keeping the log message to guide the user on how it can be changed.

fix: fallback to string type for unsupported format types

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/test/scala/tests/generators/dropwizard/server/DropwizardOptionalArrayParamTest.scala

Looks like I messed it up when I implemented this fix before; added a test this time to make sure it works.
The background is that Jersey can't support nested collections types as resource method parameters.  So Optional<List<T>> does not work.  Instead, we want to just unwrap that as List<T>, and Jersey will give us an empty list if it's not provided.

Actually fix DW resource optional collection param unwrapping

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sClientGenerator.scala
modules/codegen/src/test/scala/tests/core/FullyQualifiedNames.scala
modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala
modules/sample-http4s/src/test/scala/core/issues/Issue121.scala
modules/sample-http4s/src/test/scala/core/issues/Issue148.scala
modules/sample-http4s/src/test/scala/core/issues/Issue542.scala

fetch() method deprecated in http4s since 0.21.5
(see https://github.com/http4s/http4s/issues/3345)
this PR addresses it
regarding compatibility with earlier http4s versions (according to compatibility matrix - down to 0.21.0):
run() method has been added to http4s about 2 years ago
(see https://github.com/http4s/http4s/commit/1dfdbf2957dd751e707152c5d4c2071a864418fd)
so 0.21.0 should be safe

deprecated API fix

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/helpers/DropwizardHelpers.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue405.scala
modules/sample-akkaHttp/src/test/scala/generators/AkkaHttp/Client/contentType/AkkaHttpTextPlainTest.scala
modules/sample-akkaHttpJackson/src/test/scala/core/issues/Issue405.scala
modules/sample-akkaHttpJackson/src/test/scala/generators/AkkaHttp/Client/contentType/AkkaHttpTextPlainTest.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/AsyncHttpClientContentHeaderTest.scala
modules/sample-http4s/src/test/scala/generators/Http4s/Client/contentType/Http4sTextPlainTest.scala
modules/sample/src/main/resources/contentType-textPlain.yaml

Resolves #306 
Threading through `produces` into server generators, explicitly adding support for encoding `text/plain` in akka-http servers.
This also gets closer to supporting multiple supported `Content-Type`s for a single request, since the content types are threaded all the way through to the edge.

Support text/plain in akka-http server responses

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/sample-dropwizard/src/test/java/core/Dropwizard/EqualsVerifierTest.java

The Java code generator was producing an 'equals' method that could not pass the
verification logic in the [equalsverifier] library.
I have added an EqualsVerifier unit test and adjusted the Java code generator
so that Guardrail's Java classes comply with [equalsverifier]
Reference:
https://github.com/jqno/equalsverifier

fix Java 'equals' method

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/Dropwizard.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvc.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaModule.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpJackson.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Dropwizard.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Endpoints.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4s.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaModule.scala

With the recent extension of alternate collections libraries by enabling different modules, many stable `object`s were converted into `class`es. This PR reintroduces the previous static members of the containing object, reducing syntax noise for consumers.

Introducing new proxies to aide migration for codebases that extend guardrail directly

---

modules/sample-akkaHttp/src/test/scala/generators/AkkaHttp/Client/contentType/AkkaHttpTextPlainTest.scala

I found some more tests for `text/plain` internally, moving these tests to the public guardrail codebase as well.

Adding raw client text/plain tests for akka-http

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
modules/codegen/src/test/scala/com/twilio/guardrail/generators/syntax/JavaSyntaxTest.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala
modules/codegen/src/test/scala/tests/generators/dropwizard/JacksonGetterTest.scala
modules/codegen/src/test/scala/tests/generators/dropwizardScala/server/DropwizardScalaJsr310Test.scala

Addresses https://github.com/twilio/guardrail/issues/862

Fix Object.getClass() clash with DTO properties named "class"

---

modules/codegen/src/main/scala/com/twilio/guardrail/core/Tracker.scala

In the scaladoc, it looks like the variable `tracker` should be `servers`.

Fix typo in Tracker scaladoc

---

modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala

Documenting initial investigatory work for integrating better error messages from OpenAPIParser

Emitting OpenAPI parser warnings

---

build.sbt

"Similar to publishLocal, publishM2 task will publish to the user’s Maven local repository."
https://www.scala-sbt.org/1.x/docs/Publishing.html

add SBT command alias:  publishM2

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/CollectionsAbstraction.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaCollectionsHelpers.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaStdLibCollections.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaVavrCollections.scala
modules/codegen/src/test/scala/com/twilio/guardrail/collections/CollectionsAbstractionTest.scala

Properly handles the need to call `stream()` when starting "monadic operations" on `java.util.List`, and then `collect(Collectors.toList())` when finishing.  I do this by creating a `TermHolder` subclass that is used _after_ `stream()` has been called.  This way multiple monadic calls will not require a round trip between `Stream` and `List`.
Also adds `.toArray()` and `.filter()` to the collections abstraction.

Fix stdlib collections stream/collect

---

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala
modules/codegen/src/main/scala/com/twilio/guardrail/WriteTree.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
modules/codegen/src/test/scala/com/twilio/guardrail/core/WriteTreeSuite.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/AsyncHttpClientContentHeaderTest.scala
modules/sample-dropwizard/src/test/scala/core/Dropwizard/JavaInvalidCharacterEscapingTest.scala

1. Deduplicated `WriteTree` sprawl in Scala and Java generators
2. Made `WriteTree` contain `Future[Target[Array[Byte]]]` so the render can safely fail
3. Incorporated that failure into the main runner instead of just throwing an exception

Formatting race condition redux

---

build.sbt
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sHelper.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Content.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sMixedContentTypesTest.scala
modules/sample/src/main/resources/mixed-content-types-3.0.2.yaml

OpenAPI 3.x allows to define a content type per a response, but in Swagger 2.x you have to define `produces` for an operation. Swagger automatically converts operation without `produces` to content type `application/json`. In the existing code base a response without `produces` is converted to `Response` with content type `*/*`. So I have created new content type `AnyContentType` which is next converted to json in `Http4sHelper`. I'm not sure if it is the best solution, I have also had two other options.
this PR fixes #949 

[OAS3.0] Fixed responses with different content types for http4s

---

codecov.yml

This was going to be included with the endpoints bump, but that is taking quite a while.

Delay confusing codecov comment

---

.github/workflows/ci.yml
.github/workflows/publish-website.yml
.github/workflows/release.yml

2.6.0 isn't valid when kicking off a release, install the deps in CI to ensure we discover as early as possible.

Including deps in CI

---

.gitignore
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala

Instead of
Warning: Using `tags` to define package membership is deprecated in favor of the `x-jvm-package` vendor extension (Vector(.paths, ./store/order/{orderId}, .operations, .DELETE, .tags))
show
Warning: Using `tags` to define package membership is deprecated in favor of the `x-jvm-package` vendor extension (.paths./store/order/{orderId}.operations.DELETE.tags)

Logging tweak

---

.github/workflows/ci.yml

Reducing the maintenance burden of categorizing scala-steward PRs

Automatically tag scala-steward PRs with "chore"

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/LanguageParameter.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/EnumProtocolTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala

Resolving some dangling `(_: Tracker[A]).get` warnings. `.get` was only intended to be a stopgap, either replaced by `.unwrapTracker` or something else that uses the information stored in `Tracker[A]` more effectively, both for errors as well as safety.

Tracker deprecation

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsClientGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/JacksonProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/collections/JavaCollectionsGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaStdLibCollections.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaVavrCollections.scala

- Suppressing `Null`/`NonUnitStatements` warnings in Java generators
- Remove unused imports
- Reducing warnings by consolidating calls to reduceLeft

Reducing warnings (pt1)

---

build.sbt
modules/codegen/src/test/scala/core/TrackerTests.scala

- Resolving the last few Tracker.get warnings
- Correctly preventing wartremover from reporting in tests

Removing Tracker.get from tests

---

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/EndpointsServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala
modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala
modules/codegen/src/main/scala/com/twilio/guardrail/terms/LanguageTerms.scala
modules/codegen/src/test/scala/core/issues/Issue166.scala
modules/codegen/src/test/scala/support/SwaggerSpecRunner.scala
modules/codegen/src/test/scala/tests/core/TypesTest.scala
modules/codegen/src/test/scala/tests/generators/dropwizardScala/server/DropwizardScalaJsr310Test.scala
modules/microsite/src/main/scala/DocsHelpers.scala

In situations where we are guaranteed to need lists with at least one element, use `NonEmptyList` to communicate this.
An alternate approach would be to use `::` explicitly, but I think NEL is less error-prone.

List -> NonEmptyList conversions

---

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sNonStringEnumerationTest.scala

After thinking and discussing a bit more after #1030, I think despite the repetition, prefixing numeric enumerations with the class name will improve intelligibility long-term.
If a specification comes along that permits providing labels for numeric enumeration values, that'll certainly also improve usability.
```diff
@@ -33,10 +33,10 @@ class Http4sNonStringEnumerationTest extends AnyFunSuite with Matchers with Eith
}
test("round-trip: Ensure enumerations are unpacked correctly") {
-    val expectedInt      = cdefs.IntEnum.V1
-    val expectedLong     = cdefs.LongEnum.V2
+    val expectedInt      = cdefs.IntEnum.IntEnum1
+    val expectedLong     = cdefs.LongEnum.LongEnum2
val expectedString   = cdefs.StringEnum.ILikeSpaces
-    val expectedBody     = cdefs.IntEnum.V3
+    val …
```

Renaming confusing integer enum fields from V${num} to ${clsName}${num}

---

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sHelper.scala

Small change to allow for subtypes of application/json contenttype to be recognized for generating entityEncoder/decoder 
For example useful when types such as `application/problem+json` are used to indicate more specifically what kind of content an entity is represented by.

HTTP4s - Add support for subtypes of application/json 

---

modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala
modules/codegen/src/test/scala/core/issues/Issue313.scala

Resolve #313 
Extending from #424, I didn't realize that @sbrunk already wrote exactly this before, but I hadn't encountered it myself, so I'm using the metadata from that commit to recognize the effort put forward at that time.

Only permit generating a body parameter for non-form content types

---

build.sbt

Some of these packages have started being compiled against Java 11, which means users building their projects with a JDK8 distribution will fail to build (even though the generated code could of course run on Java 8).  These packages are somewhat odd in that many specify an allowed version range, rather than a specific version, of their dependencies.  So all of our existing releases through summer 2019 have likely stopped working over the last month or so when the toolchain used is JDK8.

Pin various eclipse java formatter versions

---

modules/codegen/src/main/scala/dev/guardrail/generators/Java/JacksonGenerator.scala
modules/codegen/src/main/scala/dev/guardrail/generators/syntax/Java.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonPropertyTest.scala

If a primitive type is specified but no value is present in the JSON string, Jackson will pass its zero value to the constructor.  Using
boxed types in the constructor allows Jackson to pass `null` to the constructor, which we can catch.

Ensure deser failure when primitive type is missing in Jackson DTOs

---

build.sbt

slf4j implementations are supplied by sbt and maven, so just hardcode slf4j-simple when running `cli` at the sbt prompt

Using slf4j-simple for development cli command

---

modules/codegen/src/test/scala/core/issues/Issue165.scala
modules/codegen/src/test/scala/tests/generators/http4s/Http4sServerTest.scala
modules/core/src/main/scala/dev/guardrail/ServerGenerator.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/Scala/Http4sServerGenerator.scala

Resolves #1229 
My understanding is that since the path extractor happens first, there's no problem with reordering paths like this. Additionally, since users can define functions in whatever order in their implementations, there's no user-facing change here, other than fixing the path matching bug.

Sorting http4s route matching based on first templated variable

---

.github/release-drafter-core.yml
.github/release-drafter-guardrail.yml
.github/release-drafter-java-async-http.yml
.github/release-drafter-java-dropwizard.yml
.github/release-drafter-java-spring-mvc.yml
.github/release-drafter-java-support.yml
.github/release-drafter-scala-akka-http.yml
.github/release-drafter-scala-dropwizard.yml
.github/release-drafter-scala-endpoints.yml
.github/release-drafter-scala-http4s.yml
.github/release-drafter-scala-support.yml
.github/workflows/release.yml
build.sbt
project/version-policy.sbt
support/regenerate-release-drafter.sh

- Track not just the module directory, but also `project/` and `build.sbt` when considering release-drafter for modules
- Using `sbt-version-policy`'s `versionCheck` to ensure bincompat on release so we can rely on `provided` scope
- Using sbt's built-in `versionScheme := Some("early-semver")` to ensure that dependency evictions cause an error
- Adding `support/regenerate-release-drafter.sh` to make it easier to generate the release infrastructure boilerplate

Ensuring bincompat for guardrail modules

---

modules/java-support/src/main/scala/dev/guardrail/generators/Java/JacksonGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/generators/syntax/Java.scala
modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonEmptyIsNullTest.scala
modules/sample-dropwizardScala/src/test/scala/core/Jackson/JacksonEmptyIsNullTest.scala
modules/sample/src/main/resources/empty-is-null.yaml
modules/scala-support/src/main/scala/dev/guardrail/generators/Scala/JacksonProtocolGenerator.scala
project/src/main/scala/RegressionTests.scala

Closes #1257 
(Bonus: beyond #1257, this implements it for scala/jackson as well as java/jackson. Unbonus: this does _not_ work when using the new-style `Presence` stuff; only the legacy handling supports this for now.)

Support `x-empty-is-null` when generating Jackson-annotated DTOs

---

build.sbt
support/regenerate-release-drafter.sh

It looks like after the language prefix stuff was added, `runExample` stopped parsing since the language prefix switching from scala to java was included in the middle of the CLI args, which then switched the language for the initially parsed arguments.

runExample bugfix, regenerate release-drafter additions

---

.github/release-drafter-cli.yml
.github/release-drafter-core.yml
.github/release-drafter-guardrail.yml
.github/release-drafter-java-async-http.yml
.github/release-drafter-java-dropwizard.yml
.github/release-drafter-java-spring-mvc.yml
.github/release-drafter-java-support.yml
.github/release-drafter-scala-akka-http.yml
.github/release-drafter-scala-dropwizard.yml
.github/release-drafter-scala-endpoints.yml
.github/release-drafter-scala-http4s.yml
.github/release-drafter-scala-support.yml
project/src/main/scala/Build.scala
support/regenerate-release-drafter.sh

This will make builds more stable at the expense of pain during release.
If the pain is great enough, it may be sufficient to do a publishLocal
for dependencies from known tags instead of waiting for a repository
sync.
Initially we were just faking it by pretending that master had the same
ABI as releases because the release script triggers new releases in
order, but this was always a trick, albeit one that I believed would
work.

When releasing, explicitly depend on published jar

---

modules/sample-http4s/src/test/scala/core/Http4s/Http4sCustomExtractorTest.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sDebugBodyTest.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sFullTracerTest.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sMixedContentTypesTest.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sNonStringEnumerationTest.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sRawServerTest.scala
modules/sample-http4s/src/test/scala/core/Http4s/Http4sRoundTripTest.scala
modules/sample-http4s/src/test/scala/core/issues/Issue121.scala
modules/sample-http4s/src/test/scala/core/issues/Issue1229.scala
modules/sample-http4s/src/test/scala/core/issues/Issue148.scala
modules/sample-http4s/src/test/scala/core/issues/Issue455.scala
modules/sample-http4s/src/test/scala/core/issues/Issue542.scala
modules/sample-http4s/src/test/scala/generators/Http4s/Client/contentType/Http4sTextPlainTest.scala
modules/sample-http4s/src/test/scala/generators/Http4s/RoundTrip/Http4sCustomHeadersTest.scala
modules/sample-http4s/src/test/scala/generators/Http4s/RoundTrip/Http4sFormDataTest.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala

The change repeats the same solution as in akka-http generator. The main problem is solves is to make it possible to generate both a server and a client to the same package. The best solution would be to reuse the same response definitions on both sides but it requires a wider change

Move http4s response defs to local scope

---

build.sbt

The root project now correctly depends on all constituent modules instead of using the custom ones. This makes `cli` and related developer tooling work again.

Resolving CLI runner dependency issues

---

.github/workflows/ci.yml
project/src/main/scala/Build.scala
support/current-pr-labels.sh

During CI, unless `major` or `minor` are explicitly specified, we should restrict to the current ABI for all modules

Test bincompat CI extensions

---

.github/workflows/ci.yml

Recently Java runtime tests have been just interrupted partway through,
so splitting up the frameworks in order to limit each individual runtime

Split out Java frameworks

---

modules/microsite/src/main/scala/DocsHelpers.scala

`Either#right#get` was always unsafe, but started warning in 2.13.
The unchecked casts they are replaced with are equally unsafe. More straightforward alternatives like going through `.toOption#get` or `throw new NoSuchElementException(...)` are disallowed by wartremover. At least this sticks out like a sore thumb.
The update to scalafmt comes for free as a rider, because I didn't look properly when committing and also it's nice to move it along, but I'm happy to remove it if it's too unprincipled to smuggle it in on an unrelated PR.

suppress warnings for unchecked narrowing

---

build.sbt
modules/sample-dropwizardVavr/src/test/java/core/DropwizardVavr/DropwizardJsr310Test.java

- When switching from sbt alias' to `taskKey`, I didn't know or realize that `run / fork := true` would no longer apply, impacting `runScalaExample`/`runJavaExample`/`runExample`, causing them to `exit(n)` after every run, taking down sbt with it
- Setting the jersey port bind property before running JSR310 tests to avoid port bind conflicts

Resolving some infrastructure issues

---

modules/core/src/main/scala/dev/guardrail/SwaggerUtil.scala
modules/core/src/main/scala/dev/guardrail/generators/ProtocolGenerator.scala
modules/microsite/src/main/scala/DocsHelpers.scala
modules/sample/src/main/resources/response-headers.yaml
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala
modules/scala-http4s/src/test/scala/core/issues/Issue144.scala
modules/scala-http4s/src/test/scala/core/issues/Issue165.scala
modules/scala-http4s/src/test/scala/core/issues/Issue166.scala
modules/scala-http4s/src/test/scala/core/issues/Issue223.scala
modules/scala-http4s/src/test/scala/core/issues/Issue225.scala
modules/scala-http4s/src/test/scala/core/issues/Issue255.scala
modules/scala-http4s/src/test/scala/core/issues/Issue260.scala
modules/scala-http4s/src/test/scala/core/issues/Issue370.scala
modules/scala-http4s/src/test/scala/core/issues/Issue416.scala
modules/scala-http4s/src/test/scala/core/issues/Issue420.scala
modules/scala-http4s/src/test/scala/core/issues/Issue429.scala
modules/scala-http4s/src/test/scala/tests/core/FullyQualifiedNames.scala
modules/scala-http4s/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala

With a bit of doing, `modelMetaType` and `propMetaImpl` ended up being able to be unified. Both were nearly identical implementations, but stemmed from the fact that in swagger 2.0 days, `model` and `prop` were different type families. After OpenAPI unified them, this became possible.

Unify model and prop meta

---

modules/codegen/src/test/scala/tests/core/DereferencingAliasesSpec.scala
modules/core/src/main/scala/dev/guardrail/SwaggerUtil.scala
modules/core/src/main/scala/dev/guardrail/generators/LanguageParameter.scala
modules/core/src/main/scala/dev/guardrail/terms/SwaggerTerms.scala

Resolves #1313 
- Bubbling `required` into `paramMeta` to permit `required: true` to be tracked through `#/components/parameters/...`

Fix `required` not being followed by `$ref`'d parameters

---

build.sbt
modules/cli/src/main/scala/dev/guardrail/cli/CLICommon.scala
modules/core/src/main/scala/dev/guardrail/Args.scala
modules/core/src/main/scala/dev/guardrail/Common.scala
modules/core/src/main/scala/dev/guardrail/Context.scala
modules/core/src/main/scala/dev/guardrail/generators/ProtocolGenerator.scala
modules/core/src/main/scala/dev/guardrail/generators/SwaggerGenerator.scala
modules/core/src/main/scala/dev/guardrail/terms/SwaggerTerms.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala
project/src/main/scala/RegressionTests.scala

In response to some objections to removing the conversion of `tags: [a,b,c]` into package components (eg: `com.example.foo.a.b.c....`), adding a CLI flag, ~`--tags-are-packages`~ `--package-from-tags`, to retain that behaviour but to get rid of that warning.

Promoting determining packages from tags to a feature instead of deprecated

---

build.sbt
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala

- No need to try to go back to `forProductN`, since the complexity vs additional functionality we get by manually emitting encoders and decoders isn't worth it
- Turns out we were running `test` twice, once outside and then again inside aliases

Removing old Circe code

---

modules/codegen/src/main/scala/dev/guardrail/generators/GeneratorMappings.scala
modules/codegen/src/main/scala/dev/guardrail/generators/scala/ScalaModule.scala
modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
modules/core/src/main/scala/dev/guardrail/Target.scala
modules/core/src/main/scala/dev/guardrail/core/CoreTermInterp.scala

- Frameworks are now just `NEL[String]`, where the strings are the constituent modules
- Unifying module version specification as `${module}-v{version}`, `circe-0.11` -> `circe-v0.11`

Start to break up frameworks

---

modules/codegen/src/main/scala/dev/guardrail/generators/scala/ScalaModule.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttp.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpClientGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpHelper.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpJackson.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpPathExtractor.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpVersion.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardClientGenerator.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardServerGenerator.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardVersion.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/CirceModelGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/JacksonModelGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ModelGeneratorType.scala

Moving towards SPI, there's no value in the `sealed` aspect of these version trackers.
Additionally, by moving these version trackers out further down into modules, it avoids the need to unnecessarily bump the core libs

Break up `ModelGeneratorTypes` sealed trait

---

project/src/main/scala/Build.scala

I mistakenly assumed that release.yml also had `GUARDRAIL_CI`. Better to just re-establish the previous flow here instead of messing with the workflow definitions.

isRelease should be considered for bincompat

---

modules/core/src/main/scala/dev/guardrail/terms/Content.scala
modules/core/src/main/scala/dev/guardrail/terms/RouteMeta.scala
modules/java-async-http/src/main/scala/dev/guardrail/generators/java/asyncHttpClient/AsyncHttpClientClientGenerator.scala
modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardServerGenerator.scala
modules/java-spring-mvc/src/main/scala/dev/guardrail/generators/java/springMvc/SpringMvcServerGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/java/helpers/ResponseHelpers.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpClientGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpHelper.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardServerGenerator.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sClientGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ResponseADTHelper.scala
modules/scala-support/src/main/scala/dev/guardrail/scala/helpers/ResponseHelpers.scala

A stub for now, but wiring through the scope parameter to `ApplicationJson` to enable #1120

Extending application/json with an optional Scope

---

modules/core/src/main/scala/dev/guardrail/SwaggerUtil.scala

An unintended consequence of #1407 was missing `*Schema` mappings causing the underlying raw types to be interpolated directly into generated sources.
Add more mappings, as well as a `println` to help track down further issues.

Adding missing Schema mappings

---

modules/core/src/main/scala/dev/guardrail/generators/spi/AbstractLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ClientGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/CollectionsGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/FrameworkGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/FrameworkLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/LanguageLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ModuleMapperLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ProtocolGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ServerGeneratorLoader.scala

- Abstract out the commonalities in the various SPI loaders
- Change `TypeTag#==` to `TypeTag.tpe#=:=` for more accurate and stable SPI type binding comparisons

Better TypeTag comparison

---

modules/core/src/main/scala/dev/guardrail/generators/spi/AbstractLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ClientGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/CollectionsGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/FrameworkGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/FrameworkLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/LanguageLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ProtocolGeneratorLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ServerGeneratorLoader.scala

Deferring this to at some point in the future to avoid breaking bincompat.
Turns out it wasn't actually used anyway.

Reverting AbstractGeneratorLoader parameter abstraction

---

modules/core/src/main/scala/dev/guardrail/generators/ProtocolGenerator.scala
modules/sample-springMvc/src/test/scala/alias/server/springMvc/foo/AliasSpecs.scala
modules/sample/src/main/resources/alias.yaml

Resolves #1502 
Following @djm1329's investigation, `StringSchema` was using `modelTypeAlias`, which wasn't designed to handle primitive type aliases. This may have been a hold-over from before the object model was standardized in `swagger-parser`, or perhaps it's just been a bug forever and #1407 exposed it.
This'll be a `bugfix`, not a `minor`, but due to `early-semver` seeming to be incompatible with `dependsOn`, the only way to get the tests to run successfully currently is to use `minor` to disable the `early-semver` check.

StringSchema incorrectly treated as a model

---

modules/cli/src/main/scala/dev/guardrail/cli/CLICommon.scala

During #1497 I removed the `getOrElse("scala")`, incorrectly presuming that the first argument would always be a language identifier.
In so doing, I introduced a situation where the `CoreTermLoader` could be passed a CLI argument, as previous semantics presumed that the leading argument was only optionally a language specifier, leading to confusing error messages for CLI users.

Better default language handling for CLI parser

---

.github/workflows/ci.yml
modules/sample-http4s/src/test/scala/generators/Http4s/Client/contentType/Http4sTextPlainTest.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sClientGenerator.scala
modules/scala-http4s/src/test/scala/tests/core/FullyQualifiedNames.scala
modules/scala-http4s/src/test/scala/tests/generators/http4s/BasicTest.scala
modules/scala-http4s/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala

Resolve #1424 
- Introduce a `ContentType` mapping and rendering them into a common `org.http4s.headers.Accept` header

Introducing acceptHeader to http4s client generator

---

project/src/main/scala/Build.scala

This was a mistake.
We already have `early-semver` guaratees during CI, but including this in the publishing POM ensures that independent 0.x versions are incompatible, even though we know they are.

Revert versionScheme in the project

---

project/src/main/scala/Build.scala

Follow-up to #1504, which actually disables it.

Actually disable versionScheme, somehow early-semver was still being picked up

---

build.sbt
modules/cli/src/main/scala/dev/guardrail/cli/CLI.scala
modules/cli/src/main/scala/dev/guardrail/cli/CLICommon.scala
modules/cli/src/test/scala/CLICommonSpec.scala
modules/core/src/main/scala/dev/guardrail/Args.scala
modules/core/src/main/scala/dev/guardrail/Error.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/AbstractLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/FrameworkLoader.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ModuleLoadResult.scala
modules/core/src/main/scala/dev/guardrail/generators/spi/ModuleMapperLoader.scala
modules/core/src/test/scala/dev/guardrail/generators/spi/ModuleLoadResultSpec.scala
modules/java-async-http/src/main/scala/dev/guardrail/generators/java/asyncHttpClient/AsyncHttpClientClientGenerator.scala
modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardGenerator.scala
modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardServerGenerator.scala
modules/java-spring-mvc/src/main/scala/dev/guardrail/generators/java/springMvc/SpringMvcGenerator.scala
modules/java-spring-mvc/src/main/scala/dev/guardrail/generators/java/springMvc/SpringMvcServerGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/JavaModuleMapper.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpClientGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardClientGenerator.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardGenerator.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardServerGenerator.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sClientGenerator.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sGenerator.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ScalaModuleMapper.scala
project/src/main/scala/RegressionTests.scala
src/test/scala/dev/guardrail/generators/spi/SpiTest.scala

- Instead of just highlighting which components did not have a module specified, collect the mapping of components to available choices to aide in the user choosing sensible values.

Including available choices

---

.github/labeler.yml
modules/java-async-http/src/main/scala/dev/guardrail/generators/java/asyncHttpClient/AsyncHttpClientClientGenerator.scala
modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardServerGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/java/helpers/ResponseHelpers.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpClientGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpGenerator.scala
modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpHelper.scala
modules/scala-akka-http/src/test/scala/core/issues/Issue43.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardServerGenerator.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala
modules/scala-http4s/src/test/scala/tests/generators/http4s/Http4sServerTest.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ResponseADTHelper.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/scala/helpers/ResponseHelpers.scala
project/src/main/scala/modules/core.scala
src/test/scala/tests/core/PathParserSpec.scala

As raised in #1530, `io.circe.Error` is a particularly common term to show up in a specification file, so use fully qualified class names and remove unnecessary imports.

Resolve overly broad circe imports

---

.github/release-drafter-cli.yml
.github/release-drafter-core.yml
.github/release-drafter-java-async-http.yml
.github/release-drafter-java-dropwizard.yml
.github/release-drafter-java-spring-mvc.yml
.github/release-drafter-java-support.yml
.github/release-drafter-scala-akka-http.yml
.github/release-drafter-scala-dropwizard.yml
.github/release-drafter-scala-http4s.yml
.github/release-drafter-scala-support.yml
.github/release-drafter.yml
support/regenerate-release-drafter.sh

Now the main release-drafter.yml does not need to managed by the script and you can simply modify it once.

use extends to avoid duplicate config

---

modules/core/src/main/scala/dev/guardrail/SwaggerUtil.scala

Fixes #1592 
Oversight when using `unwrapTracker` on the fallback projection. `unwrapTracker` falsely gave the impression that all was handled, `unapply` would have clearly communicated that we need to do something with the history string.

Adding Tracker history for fallback errors

---

build.sbt
modules/core/src/main/scala/dev/guardrail/core/PathExtractor.scala
modules/sample/src/main/resources/issues/issue1594.yaml
project/src/main/scala/RegressionTests.scala
src/test/scala/tests/core/PathParserSpec.scala

Fixes #1594 
From the [whatwg spec](https://url.spec.whatwg.org/#urls), `https://example.org//` should be permitted.

Adding proper support for empty path segments

---

modules/core/src/main/scala/dev/guardrail/SwaggerUtil.scala

Resolves #1597
While StructuredLogger is still out of commission, we don't have a great way to do deferred logging. The result of `determineTypeName` really should be `F[(F[L#Type], ReifiedRawType)]`, permitting us to delay effects until we know we need them.
In the meantime though, just suppress the warning if we clearly have a type override present.

Suppress "Deprecated behavior" log if x-${lang}-type is present

---

modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala
modules/scala-akka-http/src/test/scala/core/issues/Issue1682.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala
modules/scala-http4s/src/test/scala/core/issues/Issue1682.scala

Also added minimal test cases to show that the "Unknown method" error no longer occurs.

Added support for HTTP HEAD method for akka-http and http4s

---

modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala
modules/scala-http4s/src/test/scala/core/issues/Issue144.scala
modules/scala-http4s/src/test/scala/core/issues/Issue416.scala
modules/scala-http4s/src/test/scala/tests/generators/http4s/Http4sServerTest.scala

Making encoders protected allows to overwrite them a provide a customized version (particularly to use streamJsonArrayEncoderOf instead of jsonEcnoderOf for Streams)
```
new SomeResource[F] {
override  protected[this] val someOkEncoder = streamJsonArrayEncoderOf[F, fs2.Streamr[Entity]]
}
```
(not sure of the right collaboration protocol, let me know if something else is needed :) )

Make resource vals protected

---

build.sbt
modules/core/src/main/scala/dev/guardrail/core/Tracker.scala
modules/core/src/main/scala/dev/guardrail/core/extract/package.scala
modules/core/src/main/scala/dev/guardrail/core/resolvers/ModelResolver.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/syntax/Java.scala
modules/scala-akka-http/src/test/scala/core/issues/Issue145.scala
modules/scala-akka-http/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala
modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sClientGenerator.scala

In preparation for 1.0.0, delete deprecated methods and `println`'s.

Remove deprecations

---

modules/cli/src/main/scala/dev/guardrail/cli/CLICommon.scala
modules/core/src/main/scala/dev/guardrail/Target.scala
modules/core/src/main/scala/dev/guardrail/core/StructuredLogger.scala
src/test/scala/core/StructuredLoggerSuite.scala

There was an issue with `prependLogger` which ended up actually duplicating log lines instead of only prepending them.

Resolve structured logger log duplication

---

modules/core/src/main/scala/dev/guardrail/terms/CoreTerms.scala
modules/java-async-http/src/main/scala/dev/guardrail/generators/java/asyncHttpClient/AsyncHttpClientClientGenerator.scala
modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardServerGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonHelpers.scala
modules/java-support/src/main/scala/dev/guardrail/java/helpers/ResponseHelpers.scala
modules/java-support/src/test/scala/tests/generators/helpers/JacksonHelpersTest.scala
modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardServerGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceRefinedProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonHelpers.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/scala/helpers/ResponseHelpers.scala
modules/scala-support/src/test/scala/tests/generators/helpers/JacksonHelpersTest.scala

- Any interpreters provided in `$lang-support` modules should be fully scoped to the languages they operate in.
- Remove unnecessary `CoreTerms. coreTerm` as that pattern is now unused

Avoid LA in language modules

---

modules/cli/src/main/scala/dev/guardrail/cli/CLICommon.scala
modules/core/src/main/scala/dev/guardrail/generators/SwaggerGenerator.scala

- Reflow to avoid reimplementing `raiseErrorIfEmpty`
- Remove `unsafePrintHelp()` from `UserError` in CLI driver

Minor cleanup

---

modules/core/src/main/scala/dev/guardrail/core/extract/VendorExtension.scala
modules/core/src/main/scala/dev/guardrail/core/resolvers/ModelResolver.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceRefinedProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala
src/test/scala/core/issues/Issue1854.scala

~~If spec would contain paths that use said schemas, then models would be generated.~~ https://github.com/guardrail-dev/guardrail/pull/1854#issuecomment-1780667775

OpenAPI v3.1.0 spec files do not generate valid data classes

---

modules/core/src/main/scala/dev/guardrail/core/ResolvedType.scala
modules/core/src/main/scala/dev/guardrail/core/resolvers/ModelResolver.scala
modules/core/src/main/scala/dev/guardrail/generators/LanguageParameter.scala
modules/core/src/main/scala/dev/guardrail/terms/OpenAPITerms.scala
modules/core/src/main/scala/dev/guardrail/terms/protocol/PropMeta.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceRefinedProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala
project/WelcomeMessage.scala
src/test/scala/tests/core/EscapeTreeSpec.scala

Part of the problem with the type hierarchy here is that even though it's convenient, `Resolved` should never be conflated with `LazyResolved`. That conflation led to #1873 sticking around for so long.

Breaking `Resolved[L]` out from lazy protocol objects

---

project/src/main/scala/Build.scala
support/current-pr-labels.sh

- Incorporate some of the version bumping semantics from release-drafter into `support/current-pr-labels.sh`
- Always search for PR labels, even if we are not running inside GitHub (or not inside a PR)
- Disambiguate `moduleName` (`guardrail-core`) vs `moduleSegment` (`core`)

Better snapshot version numbers

---

modules/core/src/main/scala/dev/guardrail/Common.scala

Resolve #1897 
Ideally we'd have proper support for different servers with interpolated variables, but until that happens let's just filter them out.

Filter out server URLs that accept template variables

---

.github/workflows/ci.yml
project/src/main/scala/Build.scala
support/apply-pr-label-locally.sh
support/current-pr-labels.sh

Avoid duplicating work. After #1895, local version tagging occurs twice.
Disable the legacy one, as the new version also applies to manually releasing modules via GHA

Rely entirely on custom version mangling inside sbt

---

modules/core/src/main/scala/dev/guardrail/WriteTree.scala
modules/core/src/main/scala/dev/guardrail/terms/LanguageTerms.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/JavaGenerator.scala
modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala
modules/sample-akkaHttp/src/test/scala/core/issues/Issue195.scala
modules/sample/src/main/resources/issues/issue195.yaml
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ScalaGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceRefinedProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala

Resolve #1904 
`oneOf`, when used in `properties`, emits broken code.
This PR unfortunately ran into an issue with `PropMeta`, wherein `ModelResolver` has no way to distinguish between guardrail-generated models and just other types that exist on the JVM. I worked around this by testing whether the type is leading with the fully-qualified to the wrapping class.
Relying on tests to keep this working for now, until a ModelResolver refactor.

Resolve 1904

---

modules/sample/src/main/resources/issues/issue222.yaml
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceRefinedProtocolGenerator.scala
modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala

Resolves #1642
For generated DTOs, ensure parameters are deduplicated. Required parameters take priority over optional ones in the case of conflicts where the base types are the same.

Distinct protocol parameters

---

modules/sample/src/main/resources/issues/issue264.yaml

Typo when converting from swagger, presumably

Fix parser warning for #264
