guardrail-dev/guardrail

build.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/ReadSwagger.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala, modules/sample/src/main/resources/contentType-textPlain.yaml, modules/sample/src/test/scala/generators/AkkaHttp/Client/contentType/textPlain.scala, modules/sample/src/test/scala/scalatest/EitherTValues.scala, src/test/scala/generators/AkkaHttp/Client/contentType/textPlain.scala, src/test/scala/generators/AkkaHttp/Server.scala
Resolves #58  and the `consumes` part of #38
=> Support for text/plain, as well as a bugfix for root path matching

docs/book.md
=> Adding -Ypartial-unification note to book.md

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala, modules/codegen/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala
=> Moving fileReferences accumulator inside entity to prevent leak

build.sbt
=> Upgrading scalameta

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala, modules/codegen/src/test/scala/core/issues/Issue122.scala, modules/codegen/src/test/scala/tests/generators/akkaHttp/client/ParamConflictsTest.scala
=> Support form parameters that are arrays

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala, modules/codegen/src/test/scala/core/issues/Issue126.scala
I need server generator to support OPTIONS method for supporting CORS.
=> Support options routes

modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerm.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala
=> Refactor buildTracingFields to be overridable

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/extract/Extractable.scala, modules/codegen/src/main/scala/com/twilio/guardrail/extract/package.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala, modules/codegen/src/test/scala/core/issues/Issue145.scala
=> Fix emptyToNull not working correctly with snake-cased parameters

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
Factors out the DW response class creators into two public methods: `generateResponseSuperClass()` and `generateResponseClass()`.  The latter now has an optional parameter, `errorEntityFallbackType`, which can be used to specify an entity type for 4xx and 5xx errors if the Swagger spec does not specify an entity body for those types.  Useful for allowing/enforcing particular formats for error responses in sub-interpreters.
=> Factor out DW response class creators into public methods

modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/framework/FrameworkTerm.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/framework/FrameworkTerms.scala
=> Make GetFrameworkDefinitions aware if tracing is enabled or not

build.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
Don't write code when someone else already did it.
=> Remove RichJavaOptional in favor of scala-java8-compat

modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala
=> Allow loadSupportDefinitionFromString() to load interfaces as well

build.sbt
=> Bumped version of swagger parser

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
Addresses https://github.com/twilio/guardrail/issues/248
=> Dropwizard: support x-server-raw-response vendor extension

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
Addresses https://github.com/twilio/guardrail/issues/246
=> Allow passing Optional<T> values to Java POJO and client call builders

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala
Depends on https://github.com/twilio/guardrail/pull/252
Addresses https://github.com/twilio/guardrail/issues/242
=> Add a copy constructor for Jackson POJOs

modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala
Also beefs up the logging around a few missing things so spec authors can find the issue easier.
=> Fix NPEs in SwaggerGenerator schema type extraction

.travis.yml, build.sbt
=> Removing 2.11 from cross-build

build.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
It's sooooo much nicer than Google's.
=> Use the Eclipse JDT formatter to format Java code

modules/codegen/src/main/scala/com/twilio/guardrail/ClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/Common.scala, modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala, modules/codegen/src/main/scala/com/twilio/guardrail/extract/Extractable.scala, modules/codegen/src/main/scala/com/twilio/guardrail/extract/VendorExtension.scala, modules/codegen/src/main/scala/com/twilio/guardrail/extract/package.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/client/ClientTerm.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/client/ClientTerms.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerm.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/server/ServerTerms.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerm.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala
This doesn't yet add security support to any client/server generators, but threads through the defined security schemes to enable that.
=> Security plumbing

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala
If the openapi spec gives us a `baseUrl` or `clientName`, we want to initialize it as the default, but allow overriding using a method on the builder (so no `final` modifier on the instance var).  If there is none provided, we take it in the constructor and offer no means to override (so yes `final` modifier on the instance var).
A side note: it looks like `FieldDeclaration#setFinal()` doesn't really work.  Odd.
=> Remove AHC baseUrl/clientName final modifier when we don't want it

modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
Resolves https://github.com/twilio/guardrail/issues/322
=> Support $ref inside schema inside parameter

build.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SerializationHelpers.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerm.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/ScalaTerms.scala, modules/codegen/src/test/scala/core/issues/Issue223.scala, modules/codegen/src/test/scala/tests/core/RequestBodiesTest.scala, modules/sample-dropwizard/src/test/scala/core/Dropwizard/DropwizardShowerTest.scala, modules/sample/src/main/resources/issues/issue223.yaml
I've taken a stab at UUID support (#223).
=> Add Support for UUID formatted Strings. Fixes #223

modules/codegen/src/main/scala/com/twilio/guardrail/CLI.scala, modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala, modules/codegen/src/main/scala/com/twilio/guardrail/core/StructuredLogger.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/package.scala, modules/codegen/src/test/scala/core/StructuredLoggerSuite.scala
Removing deprecated `LogAdapter` to remove confusion.
=> Removing deprecated LogAdapter

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
These functions have not been used for a while; I kept them to ease the transition for anyone with custom servers/clients that are using them, but now it is time for them to go.
=> Deleting old functions

modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaParameter.scala
`x-jvm-type` should be possible on the `schema` objects nested inside `parameter`s in OpenAPI specifications
=> Look at param and schema for custom type names

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala
This also boxes all primitive types in resource method args so that Jersey can actually apply the `@NotNull` annotation.  If primitive types are used, and the param isn't provided in the request, Jersey will just default it to `0`/`0.0`/`false`.
Addresses https://github.com/twilio/guardrail/issues/372
=> Add @NotNull to required parameters of DW resource methods

.travis.yml, build.sbt, github.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/core/StructuredLogger.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/package.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/SwaggerTerms.scala, project/plugins.sbt
=> add jdk11 build in .travis.yml

README.md, docs/book.md, docs/plugins/maven.md, docs/plugins/sbt.md
=> Updating links from book.md to https://guardrail.dev

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala, modules/codegen/src/test/scala/core/issues/Issue255.scala
This is a follow up for https://github.com/twilio/guardrail/issues/255#issuecomment-519844254
=> Add support for email schema

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala, modules/codegen/src/test/scala/tests/core/TypesTest.scala
=> Use nested class when a field is inherited from parent

.travis.yml, build.sbt
=> Scala 2.12.10

modules/codegen/src/main/scala/com/twilio/guardrail/WriteTree.scala, modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala, modules/codegen/src/test/scala/com/twilio/guardrail/core/WriteTreeSuite.scala
=> Write tree bugfix

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala, modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala, modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala
Fully qualified https status classes to limit conflicts
=> Fully qualified http4s status

modules/codegen/src/main/scala/com/twilio/guardrail/generators/CirceProtocolGenerator.scala, modules/codegen/src/test/scala/core/issues/Issue420.scala, project/plugins.sbt
=> Issue 420 - Ordering breaking composed objects

build.sbt, modules/codegen/src/test/scala/core/issues/Issue429.scala
=> Update Scalameta. Fixes #429

modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/EndpointsGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardGenerator.scala
"Unknown HTTP type" --> "Unknown HTTP status code"
=> improve error message for HTTP status codes

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala, modules/codegen/src/test/scala/tests/generators/http4s/BasicTest.scala, modules/codegen/src/test/scala/tests/generators/http4s/client/DefaultParametersTest.scala
Inspired by comments to my previous PR
=> Bind status codes to _root_ to make qualification total

build.sbt
=> sbt addCommandAlias "publishLocal"

build.sbt
=> org.eclipse.jdt.core 3.19.0

build.sbt
release notes: https://github.com/swagger-api/swagger-parser/releases
=> swagger-parser 2.0.16

.github/workflows/ci.yml
reference: https://github.com/actions/setup-java/releases
=> GitHub setup-java 1.2.0

.github/workflows/ci.yml
https://github.com/actions/setup-java/releases
=> use setup-java 1.2.0

build.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala, modules/sample-dropwizard/src/test/scala/core/Jackson/Issue389.scala, modules/sample/src/main/resources/issues/issue389.yaml
=> Custom contained types for Array/Map

.github/workflows/ci.yml
=> GitHub CI:  checkout@v1.2.0

.github/workflows/ci.yml, build.sbt
=> GitHub CI: add JDK 13

build.sbt
=> scalameta 4.3.0

modules/microsite/build.sbt
Adding an Analytics Tracking code
=> Adding Analytics

modules/codegen/src/main/scala/com/twilio/guardrail/core/StructuredLogger.scala
Who knew appending to List was so slow?
Locally, `testSuite` went from 6 minutes to run to only 1 minute.
=> Speeding up StructuredLogger

.github/workflows/ci.yml
notes: https://github.com/actions/checkout/releases/tag/v2.0.0
=> github: checkout@v2

.github/workflows/ci.yml
=> ci: add 'clean' to SBT command

.travis.yml
Resolving issues caused by incomplete upgrade of sbt-microsites components.
See https://github.com/47deg/sbt-microsites/issues/406#issuecomment-569217288 for more details.
=> Bumping ruby deps

build.sbt
Notes:
https://github.com/swagger-api/swagger-parser/releases
=> swagger-parser 2.0.17

build.sbt
release notes:
https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.18
=> swagger-parser 2.0.18

README.md
=> Adding Adopters section to README

.github/workflows/ci.yml, build.sbt, project/plugins.sbt
- add [sbt-scoverage]
- set coverageMinimum
=> enable code coverage

.github/workflows/ci.yml
Now that sbt-scoverage is enabled, upload the results to codecov.io
=> Adding codecov github action

modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala
During the refactor, I inadvertently prevented access to `frameworkMapping`, effectively locking off extension.
Instead, defining `extendWith` raises this functionality to a proper interface.
=> Permitting overriding CoreTermInterp members

modules/microsite/docs/java/dropwizard/generating-a-server.md, modules/microsite/docs/java/dropwizard/generating-clients.md, modules/microsite/docs/java/dropwizard/index.md, modules/microsite/docs/java/dropwizard/installation.md, modules/microsite/docs/java/dropwizard/sample-api-specification.md, modules/microsite/docs/java/dropwizard/what-is-guardrail.md
I took a first pass at writing the docs for generating a server for Dropwizard 1.3. I followed the existing akka-http guides for structure. Also got a simple implementation here https://github.com/nickfun/demowizard that I used to learn about how it all fits together. I'm unable to build the microsite on my laptop but I did build the docs folder with Jekyll and confirmed all the pages link to each other correctly.
=> Docs for java dropwizard

modules/microsite/docs/scala/akka-http/generating-clients.md
=> Fix typo in generating-clients.md

build.sbt
=> Scoverage coverageMininum 80.5

build.sbt
release notes:
https://github.com/swagger-api/swagger-parser/releases
=> swagger-parser 2.0.20

build.sbt
=> scala-java8-compat 0.9.1

MIGRATING.md
=> Add note to MIGRATING about scalafix rules

.github/workflows/ci.yml
=> ci: Java build matrix 8, 11, 13, 14

.github/workflows/ci.yml, .travis.yml, build.sbt
https://github.com/scala/scala/releases/tag/v2.12.12
=> Scala 2.12.12

modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala
Looks like I missed a couple spots.
Resolves https://github.com/twilio/guardrail/issues/707
=> Add missing formatTypeName() calls

modules/codegen/src/test/scala/core/issues/Issue144.scala
Here is a proof that the issue has been resolved and can be closed.
=> ISSUE-144: A test to prove the problem doesn't exist anymore.

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/DropwizardServerGenerator.scala
Dropwizard/Jersey doesn't (and can't) support things like `Optional<List<String>>`, so strip off the `Optional`.  If the parameter is
not specified at all, Jersey will provide an empty list.
This has been a long-standing bug that I never got around to fixing until now.
=> dropwizard: unwrap optional colletions types

modules/codegen/src/test/scala/core/issues/Issue314.scala
This is why I shouldn't merge branches that aren't up to date with master...
=> Fix custom classname tests

build.sbt, modules/sample-dropwizard/src/test/scala/core/Dropwizard/AsyncHttpClientContentHeaderTest.scala
=> wiremock 2.27.2

.gitignore
=> git ignore .bsp

MIGRATING.md, build.sbt, docs/plugins/make.md, docs/plugins/maven.md, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SerializationHelpers.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/syntax/Java.scala, modules/codegen/src/test/scala/core/issues/Issue314.scala, modules/microsite/docs/java/dropwizard/generating-a-server.md, modules/microsite/docs/java/dropwizard/generating-clients.md, modules/microsite/docs/java/dropwizard/installation.md
=> Add @javax.annotations.Generated to Java generators

build.sbt, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala, modules/codegen/src/test/scala/tests/generators/http4s/Http4sServerTest.scala, modules/sample-http4s/src/test/scala/core/Http4s/Http4sCustomExtractorTest.scala
related to the [pull request](https://github.com/twilio/guardrail/pull/747) to implement for akka, this adds the custom extraction option for http4s
- [ x] I acknowledge that all my contributions will be made under the project's license.
=> implement custom extraction option for http4s

modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/CollectionsAbstraction.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaStdLibCollections.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/collections/JavaVavrCollections.scala
=> Add OptionF.getOrElseNull()

modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
We suspect that the eclipse code formatter is not thread-safe, which is leading to strange, intermittent, non-deterministic test suite failures.
=> java: use a fresh formatter instance per run

.github/workflows/ci.yml, build.sbt
Attempting to run the different suites in parallel
=> Attempting to split up the different suites into different jobs

codecov.yml
=> Lower coverage target to 81%

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala
https://www.javadoc.io/doc/com.github.javaparser/javaparser-core/latest/com/github/javaparser/ast/expr/IntegerLiteralExpr.html
=> fix javaparser deprecation warnings

build.sbt, project/WelcomeMessage.scala
Structure borrowed from zio
Text generated via http://patorjk.com/software/taag/
=> Adding WelcomeMessage

.github/workflows/ci.yml, .github/workflows/publish-website.yml, .github/workflows/release.yml, build.sbt
Seems like it got missed during the travis -> github actions switchover
=> Re enable website publishing

.github/workflows/ci.yml, .github/workflows/release.yml
Trying to just get snapshot releases working
=> Snapshot release attempt 2

build.sbt
See https://github.com/sbt/sbt-git/issues/164
=> Hackily work around sbt-git issue

modules/microsite/docs/scala/akka-http/guardrail-extensions.md
Minor doc fix for guardrail extensions
=> Minor doc fix for guardrail-extensions.md

modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/Responses.scala
=> Resolve tracker warning

modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/Http4sServerGenerator.scala
=> Resolving more Tracker.get calls

modules/codegen/src/main/scala/com/twilio/guardrail/ProtocolGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala, modules/codegen/src/main/scala/com/twilio/guardrail/extract/VendorExtension.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/AsyncHttpClientClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/DropwizardServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/JacksonGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Java/SpringMvcServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/JavaGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/LanguageParameter.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpClientGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpServerGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/CirceProtocolGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala, modules/codegen/src/main/scala/com/twilio/guardrail/protocol/terms/protocol/ModelProtocolTerms.scala, modules/codegen/src/main/scala/com/twilio/guardrail/terms/LanguageTerms.scala
=> Removing Tracker.get (pt4)

.github/workflows/ci.yml, build.sbt
https://github.com/scala/scala/releases/tag/v2.12.13
=> Scala 2.12.13

.github/workflows/ci.yml, build.sbt
=> Dynamically set scala matrix versions from build.sbt versions

build.sbt
Merged #1210 too quickly, didn't realize there were two similarly named branches
=> Using slf4j-simple for cli action

build.sbt, modules/sample-http4s/src/test/scala/core/issues/Issue1229.scala, modules/sample-http4s/src/test/scala/core/issues/Issue542.scala, modules/sample/src/main/resources/department.yaml
Resolves #1229 
@justcoon Can you test this branch? It uses your provided specification, but it passes locally for me (able to hit both routes distinctly) and the generated code looks as I would expect.
=> Runtime http4s tests for #1229

.github/workflows/ci.yml
No idea how we even have `sbt` on the path. Use `olafurpg/setup-scala` to at least get a managed version from a trusted source.
=> Swap setup-java for setup-scala

.github/labeler.yml, .github/workflows/ci.yml, support/label-scala-steward-prs.sh
=> Automatically tag scala-steward PRs

build.sbt, modules/codegen/src/main/scala/dev/guardrail/generators/scala/ScalaModule.scala, modules/microsite/docs/scala/akka-http/generating-a-server.md, modules/sample-akkaHttp/src/test/scala/core/AkkaHttp/AkkaHttpFullTracerTest.scala, modules/sample-akkaHttp/src/test/scala/core/AkkaHttp/AkkaHttpRoundTripTest.scala, modules/sample-akkaHttp/src/test/scala/core/issues/Issue143.scala, modules/sample-akkaHttp/src/test/scala/core/issues/Issue315.scala, modules/sample-akkaHttp/src/test/scala/generators/AkkaHttp/Client/contentType/AkkaHttpTextPlainTest.scala, modules/sample-akkaHttp/src/test/scala/generators/AkkaHttp/RoundTrip/AkkaHttpCustomHeadersTest.scala, modules/sample-akkaHttpJackson/src/test/scala/core/AkkaHttpJackson/AkkaHttpFullTracerTest.scala, modules/sample-akkaHttpJackson/src/test/scala/core/AkkaHttpJackson/AkkaHttpJacksonRoundTripTest.scala, modules/sample-akkaHttpJackson/src/test/scala/core/issues/Issue143.scala, modules/sample-akkaHttpJackson/src/test/scala/core/issues/Issue315.scala, modules/sample-akkaHttpJackson/src/test/scala/generators/AkkaHttp/Client/contentType/AkkaHttpTextPlainTest.scala, modules/sample-akkaHttpJackson/src/test/scala/generators/AkkaHttp/RoundTrip/AkkaHttpCustomHeadersTest.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttp.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpGenerator.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpJackson.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala, modules/scala-akka-http/src/test/scala/core/issues/Issue127.scala, modules/scala-akka-http/src/test/scala/tests/generators/akkaHttp/server/FormFieldsTest.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ModelGeneratorType.scala
- Explicitly adding a 10.1.x module to permit switching away from deprecated terms
=> akka-http v10.1.x module

.github/workflows/ci.yml
https://github.com/codecov/codecov-action/blob/master/README.md
﻿
=> codecov action v2

modules/sample-http4s-v0_22/src/test/scala/core/issues/Issue455.scala, modules/sample-http4s/src/test/scala/core/Http4s/Http4sRoundTripTest.scala, modules/sample-http4s/src/test/scala/core/issues/Issue455.scala
I failed to reproduce #1218, but coming through, I fixed some left out empty parameterlists.
=> Don't omit empty parameterlist

modules/codegen/src/test/scala/dev/guardrail/generators/LanguageParameterTestAdapter.scala, modules/core/src/main/scala/dev/guardrail/SwaggerUtil.scala, modules/core/src/main/scala/dev/guardrail/core/ResolvedType.scala, modules/core/src/main/scala/dev/guardrail/generators/LanguageParameter.scala, modules/core/src/main/scala/dev/guardrail/terms/LanguageTerms.scala, modules/core/src/main/scala/dev/guardrail/terms/protocol/ProtocolParameter.scala, modules/java-support/src/main/scala/dev/guardrail/generators/java/JavaGenerator.scala, modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala, modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonHelpers.scala, modules/java-support/src/main/scala/dev/guardrail/java/helpers/ResponseHelpers.scala, modules/java-support/src/test/scala/tests/generators/helpers/JacksonHelpersTest.scala, modules/sample/src/main/resources/issues/issue1218.yaml, modules/sample/src/main/resources/issues/issue622.yaml, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala, modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ScalaGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonHelpers.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/syntax/Scala.scala, modules/scala-support/src/main/scala/dev/guardrail/scala/helpers/ResponseHelpers.scala, modules/scala-support/src/test/scala/tests/generators/helpers/JacksonHelpersTest.scala
- Represent the full hierarchy of nested raw types
=> Enhancing RawParameterType to ReifiedRawType

build.sbt, modules/core/src/main/scala/dev/guardrail/core/ResolvedType.scala, modules/core/src/main/scala/dev/guardrail/terms/LanguageTerms.scala, modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonHelpers.scala, modules/java-support/src/main/scala/dev/guardrail/java/helpers/ResponseHelpers.scala, modules/sample-http4s/src/test/scala/core/issues/Issue786.scala, modules/sample/src/main/resources/issues/issue786.yaml, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonHelpers.scala, modules/scala-support/src/main/scala/dev/guardrail/scala/helpers/ResponseHelpers.scala, project/src/main/scala/RegressionTests.scala
=> Add discriminator to circe subtypes

build.sbt, modules/sample-dropwizard/src/test/scala/core/Jackson/JacksonPropertyTest.scala, modules/sample-dropwizardVavr/src/test/scala/core/JacksonVavr/JacksonBuilderParamTest.scala, modules/sample-dropwizardVavr/src/test/scala/core/JacksonVavr/JacksonNestedTest.scala, modules/sample-dropwizardVavr/src/test/scala/core/JacksonVavr/JacksonPolyMappingTest.scala, modules/sample-springMvc/src/test/scala/alias/server/springMvc/foo/AliasSpecs.scala, modules/sample-springMvc/src/test/scala/dateTime/server/springMvc/dateTime/DateTimeSpecs.scala, modules/sample-springMvc/src/test/scala/dateTime/server/springMvc/dateTime/MockDateTimeHandlerConfiguration.scala, modules/sample-springMvc/src/test/scala/examples/server/springMvc/pet/BaselineSpecs.scala
For some reason scalafmt wasn't enabled for the sample Java frameworks
=> scalafmt for Java frameworks

modules/scala-akka-http/src/test/scala/core/issues/Issue314.scala, modules/scala-akka-http/src/test/scala/core/issues/Issue43.scala
=> Fixing broken tests for akka-http

modules/java-dropwizard/src/test/scala/scala/core/issues/Issue314.scala
Similar to #1444, change brought on by #1403
=> Fixing broken tests for dropwizard

modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ScalaGenerator.scala
This fixes generated sources compilation for Scala 3
Fixes #1387
=> explicit type annotations for implicit definitions (fixes #1387)

modules/codegen/src/main/scala/dev/guardrail/generators/GeneratorMappings.scala, modules/codegen/src/main/scala/dev/guardrail/generators/scala/ScalaModule.scala, modules/codegen/src/test/scala/codegen/WritePackageSpec.scala
- Forgot to add `scala-stdlib` to `GeneratorMappings`
- Using `CollectionsGeneratorLoader` in `ScalaModule`
=> SPI CollectionsLibTerms

modules/core/src/main/scala/dev/guardrail/Common.scala, modules/core/src/main/scala/dev/guardrail/generators/Framework.scala, modules/core/src/main/scala/dev/guardrail/terms/ProtocolTerms.scala, modules/core/src/main/scala/dev/guardrail/terms/client/ClientTerms.scala, modules/core/src/main/scala/dev/guardrail/terms/framework/FrameworkTerms.scala, modules/core/src/main/scala/dev/guardrail/terms/server/ServerTerms.scala, modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/Dropwizard.scala, modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardGenerator.scala, modules/java-spring-mvc/src/main/scala/dev/guardrail/generators/java/springMvc/SpringMvc.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttp.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpClientGenerator.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpGenerator.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpJackson.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala, modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/Dropwizard.scala, modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardClientGenerator.scala, modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardGenerator.scala, modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardServerGenerator.scala, modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4s.scala, modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sClientGenerator.scala, modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sGenerator.scala, modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala
Turns out this wasn't actually used by anything
=> Dethreading CollectionsLibTerms

modules/codegen/src/main/scala/dev/guardrail/generators/GeneratorMappings.scala, modules/codegen/src/test/scala/codegen/WritePackageSpec.scala, modules/core/src/main/scala/dev/guardrail/core/CoreTermInterp.scala
- Moving to loading the framework to module mapping via SPI
=> Utilizing ModuleMapperLoader and FrameworkLoader in GeneratorMappings

project/src/main/scala/Build.scala
Currently, any time any PR that breaks semver is merged, it break the build until the next release.
A hack here is to just disable semver checking on master, since we already gate semver both at PR time as well as later on during release, so it actually serves no useful purpose to fail master as well.
=> Disable semver on master

project/src/main/scala/Build.scala
=> Disable semver on master redux

build.sbt, support/trigger-all-releases.sh
- `java-dropwizard` should not have been depending on `java-async-http` this whole time
- Making `trigger-all-releases.sh` poll until maven central syncs
=> Release tooling

.github/release-drafter-cli.yml, .github/release-drafter-core.yml, .github/release-drafter-java-async-http.yml, .github/release-drafter-java-dropwizard.yml, .github/release-drafter-java-spring-mvc.yml, .github/release-drafter-java-support.yml, .github/release-drafter-scala-akka-http.yml, .github/release-drafter-scala-dropwizard.yml, .github/release-drafter-scala-http4s.yml, .github/release-drafter-scala-support.yml, project/src/main/scala/Build.scala, support/regenerate-release-drafter.sh
Missed this one during review, causing all modules to think they had a minor version bump
=> Fixup to the last PR, refined was added to too many places

modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala
=> Adding cats instances back in

modules/microsite/docs/scala/akka-http/dtos.md, modules/microsite/docs/scala/akka-http/index.md, modules/microsite/docs/scala/http4s/dtos.md, modules/microsite/docs/scala/http4s/index.md
=> add bare-bones documentation on encoding of bodies

.github/workflows/release.yml, project/src/main/scala/Build.scala
=> Attempt to issue snapshot releases

modules/core/src/main/scala/dev/guardrail/core/ResolvedType.scala
- Deduplicate identical codepaths
- Resolve an infinite loop during object dereference
=> Deduplicate deferred

build.sbt, modules/core/src/main/scala/dev/guardrail/core/resolvers/ModelResolver.scala, modules/java-support/src/main/scala/dev/guardrail/generators/java/jackson/JacksonGenerator.scala, modules/sample-akkaHttp/src/test/scala/core/issues/Issue195.scala, modules/sample/src/main/resources/issues/issue195.yaml, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceProtocolGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/circe/CirceRefinedProtocolGenerator.scala, modules/scala-support/src/main/scala/dev/guardrail/generators/scala/jackson/JacksonProtocolGenerator.scala
=> Add nested definitions to support in-line oneOf objects

modules/core/src/main/scala/dev/guardrail/terms/Responses.scala, modules/core/src/main/scala/dev/guardrail/terms/framework/FrameworkTerms.scala, modules/java-dropwizard/src/main/scala/dev/guardrail/generators/java/dropwizard/DropwizardGenerator.scala, modules/java-spring-mvc/src/main/scala/dev/guardrail/generators/java/springMvc/SpringMvcGenerator.scala, modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpGenerator.scala, modules/scala-dropwizard/src/main/scala/dev/guardrail/generators/scala/dropwizard/DropwizardGenerator.scala, modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sGenerator.scala, modules/scala-support/src/test/scala/tests/circe/ArrayValidationTest.scala, modules/scala-support/src/test/scala/tests/circe/BigObjectSpec.scala, modules/scala-support/src/test/scala/tests/circe/ValidationTest.scala
Add context to `Unknown HTTP status code` error:
```
[error] Error: Unknown HTTP status code: default
```
becomes
```
[error] Error: Unknown HTTP status code: default (.paths./user.operations.POST.responses.default)
```
=> Including Tracker info in lookupStatusCode
